/** 4118027526 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYSIMSIGNALLIM_INST_STATIC_H
#define DAISYSIMSIGNALLIM_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_sigout_sigoutN_184	(*((double *) &instData [184]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_sigout_sigoutN_176	(*((double *) &instData [176]))	/* Branch Reln : Size = 8 bytes. */
#define _sigout_sigoutN_flow_160	(*((long *) &instData [160]))	/* Hidden Node : Size = 4 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_152	(*((double *) &instData [152]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_sigin_vgnd_136	(*((double *) &instData [136]))	/* Branch Load Group : Size = 8 bytes. */
#define _supply_val_96	(*((double *) &instData [96]))	/* VT_REAL : Size = 8 bytes. */
#define _sigout_val_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _vpwr_44	(*((long *) &instData [44]))	/* VT_NODE : Size = 4 bytes. */
#define _vgnd_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _sigin_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _sigoutN_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _sigout_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYSIMSIGNALLIM_INST_STATIC_H */
