/** 3527771854 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYSIMDIGTOVOLT_INST_STATIC_H
#define DAISYSIMDIGTOVOLT_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_sigout_vgnd_176	(*((double *) &instData [176]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_sigout_vgnd_168	(*((double *) &instData [168]))	/* Branch Reln : Size = 8 bytes. */
#define _sigout_vgnd_flow_152	(*((long *) &instData [152]))	/* Hidden Node : Size = 4 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_144	(*((double *) &instData [144]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_sigin_vgnd_128	(*((double *) &instData [128]))	/* Branch Load Group : Size = 8 bytes. */
#define _supply_val_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _sigout_val_48	(*((double *) &instData [48]))	/* VT_REAL : Size = 8 bytes. */
#define _vpwr_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _vgnd_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _sigin_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _sigout_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYSIMDIGTOVOLT_INST_STATIC_H */
