/** 883256587 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "daisySimSupply_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int daisySimSupply_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_344 = 0.0;
_V_Static_vpwr10dig_vgnd_376 = 0.0;
_V_Static_vpwr33ana_vgnd_408 = 0.0;
_V_Static_vpwr33dig_vgnd_440 = 0.0;
_V_Static_vgnd_472 = 0.0;
_Static_d_by_di_vgnd_304 = 0.0;
_V_Static_vsub_504 = 0.0;
_Static_d_by_di_vsub_320 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);(_V_Static_vpwr10ana_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10dig_vgnd_376) += (_power10_232);ahdlDoSetLineNum ((long) 34);(_V_Static_vpwr33ana_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33dig_vgnd_440) += (_power33_280);ahdlDoSetLineNum ((long) 37);(_V_Static_vgnd_472) += ((((_globalGroundRes_112)) * ((getThruSolution(_vgnd_flow_456)))));_Static_d_by_di_vgnd_304 += ((_globalGroundRes_112));ahdlDoSetLineNum ((long) 38);(_V_Static_vsub_504) += ((((_substRes_256)) * ((getThruSolution(_vsub_flow_488)))));_Static_d_by_di_vsub_320 += ((_substRes_256));}ahdlDoSetLineNum ((long) 40);    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_328,      _V_Static_vpwr10ana_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_360,      _V_Static_vpwr10dig_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_392,      _V_Static_vpwr33ana_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_424,      _V_Static_vpwr33dig_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_456,      _V_Static_vgnd_472   ,       1.0    );
      ahdlInterAddStaticElement(*(void**)(instData + 296), -_Static_d_by_di_vgnd_304);
    ahdlInterSetAcrossQuan(      *(void **)(instData + 492),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_488,      _V_Static_vsub_504   ,       1.0    );
      ahdlInterAddStaticElement(*(void**)(instData + 312), -_Static_d_by_di_vsub_320);
    return __msgSeverity__;
} /** end of daisySimSupply_DcFuncDerLoad **/

int daisySimSupply_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_344 = 0.0;
_V_Static_vpwr10dig_vgnd_376 = 0.0;
_V_Static_vpwr33ana_vgnd_408 = 0.0;
_V_Static_vpwr33dig_vgnd_440 = 0.0;
_V_Static_vgnd_472 = 0.0;
_Static_d_by_di_vgnd_304 = 0.0;
_V_Static_vsub_504 = 0.0;
_Static_d_by_di_vsub_320 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);(_V_Static_vpwr10ana_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10dig_vgnd_376) += (_power10_232);ahdlDoSetLineNum ((long) 34);(_V_Static_vpwr33ana_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33dig_vgnd_440) += (_power33_280);ahdlDoSetLineNum ((long) 37);(_V_Static_vgnd_472) += ((((_globalGroundRes_112)) * ((getThruSolution(_vgnd_flow_456)))));ahdlDoSetLineNum ((long) 38);(_V_Static_vsub_504) += ((((_substRes_256)) * ((getThruSolution(_vsub_flow_488)))));}ahdlDoSetLineNum ((long) 40);    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_328,      _V_Static_vpwr10ana_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_360,      _V_Static_vpwr10dig_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_392,      _V_Static_vpwr33ana_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_424,      _V_Static_vpwr33dig_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_456,      _V_Static_vgnd_472   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 492),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_488,      _V_Static_vsub_504   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimSupply_DcFuncLoad **/

int daisySimSupply_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_344 = 0.0;
_V_Static_vpwr10dig_vgnd_376 = 0.0;
_V_Static_vpwr33ana_vgnd_408 = 0.0;
_V_Static_vpwr33dig_vgnd_440 = 0.0;
_V_Static_vgnd_472 = 0.0;
_Static_d_by_di_vgnd_304 = 0.0;
_V_Static_vsub_504 = 0.0;
_Static_d_by_di_vsub_320 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);(_V_Static_vpwr10ana_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10dig_vgnd_376) += (_power10_232);ahdlDoSetLineNum ((long) 34);(_V_Static_vpwr33ana_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33dig_vgnd_440) += (_power33_280);ahdlDoSetLineNum ((long) 37);(_V_Static_vgnd_472) += ((((_globalGroundRes_112)) * ((getThruSolution(_vgnd_flow_456)))));_Static_d_by_di_vgnd_304 += ((_globalGroundRes_112));ahdlDoSetLineNum ((long) 38);(_V_Static_vsub_504) += ((((_substRes_256)) * ((getThruSolution(_vsub_flow_488)))));_Static_d_by_di_vsub_320 += ((_substRes_256));}ahdlDoSetLineNum ((long) 40);    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_328,      _V_Static_vpwr10ana_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_360,      _V_Static_vpwr10dig_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_392,      _V_Static_vpwr33ana_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_424,      _V_Static_vpwr33dig_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_456,      _V_Static_vgnd_472   ,       1.0    );
      ahdlInterAddStaticElement(*(void**)(instData + 296), -_Static_d_by_di_vgnd_304);
    ahdlInterSetAcrossQuan(      *(void **)(instData + 492),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_488,      _V_Static_vsub_504   ,       1.0    );
      ahdlInterAddStaticElement(*(void**)(instData + 312), -_Static_d_by_di_vsub_320);
    return __msgSeverity__;
} /** end of daisySimSupply_TranFuncDerLoad **/

int daisySimSupply_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_344 = 0.0;
_V_Static_vpwr10dig_vgnd_376 = 0.0;
_V_Static_vpwr33ana_vgnd_408 = 0.0;
_V_Static_vpwr33dig_vgnd_440 = 0.0;
_V_Static_vgnd_472 = 0.0;
_Static_d_by_di_vgnd_304 = 0.0;
_V_Static_vsub_504 = 0.0;
_Static_d_by_di_vsub_320 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);(_V_Static_vpwr10ana_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10dig_vgnd_376) += (_power10_232);ahdlDoSetLineNum ((long) 34);(_V_Static_vpwr33ana_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33dig_vgnd_440) += (_power33_280);ahdlDoSetLineNum ((long) 37);(_V_Static_vgnd_472) += ((((_globalGroundRes_112)) * ((getThruSolution(_vgnd_flow_456)))));ahdlDoSetLineNum ((long) 38);(_V_Static_vsub_504) += ((((_substRes_256)) * ((getThruSolution(_vsub_flow_488)))));}ahdlDoSetLineNum ((long) 40);    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_328,      _V_Static_vpwr10ana_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_360,      _V_Static_vpwr10dig_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_392,      _V_Static_vpwr33ana_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_424,      _V_Static_vpwr33dig_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_456,      _V_Static_vgnd_472   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 492),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_488,      _V_Static_vsub_504   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimSupply_TranFuncLoad **/

int daisySimSupply_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


    return __msgSeverity__;
} /** end of daisySimSupply_NoiseLoadBiasDep **/

int daisySimSupply_OpPointCalc(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
    return __msgSeverity__;
} /** end of daisySimSupply_OpPointCalc **/

