/** 1984234504 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYSIMADC_INST_STATIC_H
#define DAISYSIMADC_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_DATA_0__824	(*((double *) &instData [824]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_0__816	(*((double *) &instData [816]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_0__flow_800	(*((long *) &instData [800]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_1__792	(*((double *) &instData [792]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_1__784	(*((double *) &instData [784]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_1__flow_768	(*((long *) &instData [768]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_2__760	(*((double *) &instData [760]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_2__752	(*((double *) &instData [752]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_2__flow_736	(*((long *) &instData [736]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_3__728	(*((double *) &instData [728]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_3__720	(*((double *) &instData [720]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_3__flow_704	(*((long *) &instData [704]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_4__696	(*((double *) &instData [696]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_4__688	(*((double *) &instData [688]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_4__flow_672	(*((long *) &instData [672]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_5__664	(*((double *) &instData [664]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_5__656	(*((double *) &instData [656]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_5__flow_640	(*((long *) &instData [640]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_6__632	(*((double *) &instData [632]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_6__624	(*((double *) &instData [624]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_6__flow_608	(*((long *) &instData [608]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_7__600	(*((double *) &instData [600]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_7__592	(*((double *) &instData [592]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_7__flow_580	(*((long *) &instData [580]))	/* Hidden Node : Size = 4 bytes. */
#define _i_572	(*((long *) &instData [572]))	/* VT_INT : Size = 4 bytes. */
#define _vd_312(idx)	(*((double *) &instData [312 + ((idx) * 8)]))	/* VT_REAL : FIXED ARRAY SIZE : Size = 8 bytes. */
#define _vref_280	(*((double *) &instData [280]))	/* VT_REAL : Size = 8 bytes. */
#define _vtrans_clk_240	(*((double *) &instData [240]))	/* VT_REAL : Size = 8 bytes. */
#define _vlogic_low_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _halfref_160	(*((double *) &instData [160]))	/* VT_REAL : Size = 8 bytes. */
#define _unconverted_120	(*((double *) &instData [120]))	/* VT_REAL : Size = 8 bytes. */
#define _vLogicHigh_96	(*((double *) &instData [96]))	/* VT_REAL : Size = 8 bytes. */
#define _tRiseFallDel_72	(*((double *) &instData [72]))	/* VT_REAL : Size = 8 bytes. */
#define _vclk_60	(*((long *) &instData [60]))	/* VT_NODE : Size = 4 bytes. */
#define _vin_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _DATA_16	(*((long *) &instData [16]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYSIMADC_INST_STATIC_H */
