/** 3626361542 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef SICONSIMADC_INST_STATIC_H
#define SICONSIMADC_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_DATA_0__864	(*((double *) &instData [864]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_0__856	(*((double *) &instData [856]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_0__flow_840	(*((long *) &instData [840]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_1__832	(*((double *) &instData [832]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_1__824	(*((double *) &instData [824]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_1__flow_808	(*((long *) &instData [808]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_2__800	(*((double *) &instData [800]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_2__792	(*((double *) &instData [792]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_2__flow_776	(*((long *) &instData [776]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_3__768	(*((double *) &instData [768]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_3__760	(*((double *) &instData [760]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_3__flow_744	(*((long *) &instData [744]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_4__736	(*((double *) &instData [736]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_4__728	(*((double *) &instData [728]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_4__flow_712	(*((long *) &instData [712]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_5__704	(*((double *) &instData [704]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_5__696	(*((double *) &instData [696]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_5__flow_680	(*((long *) &instData [680]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_6__672	(*((double *) &instData [672]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_6__664	(*((double *) &instData [664]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_6__flow_648	(*((long *) &instData [648]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_7__640	(*((double *) &instData [640]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_7__632	(*((double *) &instData [632]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_7__flow_616	(*((long *) &instData [616]))	/* Hidden Node : Size = 4 bytes. */
#define _i_572	(*((long *) &instData [572]))	/* VT_INT : Size = 4 bytes. */
#define _vd_312(idx)	(*((double *) &instData [312 + ((idx) * 8)]))	/* VT_REAL : FIXED ARRAY SIZE : Size = 8 bytes. */
#define _vref_280	(*((double *) &instData [280]))	/* VT_REAL : Size = 8 bytes. */
#define _vtrans_clk_240	(*((double *) &instData [240]))	/* VT_REAL : Size = 8 bytes. */
#define _vlogic_low_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _halfref_160	(*((double *) &instData [160]))	/* VT_REAL : Size = 8 bytes. */
#define _unconverted_120	(*((double *) &instData [120]))	/* VT_REAL : Size = 8 bytes. */
#define _vLogicHigh_96	(*((double *) &instData [96]))	/* VT_REAL : Size = 8 bytes. */
#define _tRiseFallDel_72	(*((double *) &instData [72]))	/* VT_REAL : Size = 8 bytes. */
#define _vclk_60	(*((long *) &instData [60]))	/* VT_NODE : Size = 4 bytes. */
#define _vin_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _DATA_16	(*((long *) &instData [16]))	/* VT_NODE : Size = 4 bytes. */


#endif /* SICONSIMADC_INST_STATIC_H */
