/** 567186872 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYSIMSTATICREG_INST_STATIC_H
#define DAISYSIMSTATICREG_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_REG_0__vgnd_840	(*((double *) &instData [840]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_0__vgnd_832	(*((double *) &instData [832]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_0__vgnd_flow_816	(*((long *) &instData [816]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_1__vgnd_808	(*((double *) &instData [808]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_1__vgnd_800	(*((double *) &instData [800]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_1__vgnd_flow_784	(*((long *) &instData [784]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_2__vgnd_776	(*((double *) &instData [776]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_2__vgnd_768	(*((double *) &instData [768]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_2__vgnd_flow_752	(*((long *) &instData [752]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_3__vgnd_744	(*((double *) &instData [744]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_3__vgnd_736	(*((double *) &instData [736]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_3__vgnd_flow_720	(*((long *) &instData [720]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_4__vgnd_712	(*((double *) &instData [712]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_4__vgnd_704	(*((double *) &instData [704]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_4__vgnd_flow_688	(*((long *) &instData [688]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_5__vgnd_680	(*((double *) &instData [680]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_5__vgnd_672	(*((double *) &instData [672]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_5__vgnd_flow_656	(*((long *) &instData [656]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_6__vgnd_648	(*((double *) &instData [648]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_6__vgnd_640	(*((double *) &instData [640]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_6__vgnd_flow_624	(*((long *) &instData [624]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_REG_7__vgnd_616	(*((double *) &instData [616]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_REG_7__vgnd_608	(*((double *) &instData [608]))	/* Branch Reln : Size = 8 bytes. */
#define _REG_7__vgnd_flow_592	(*((long *) &instData [592]))	/* Hidden Node : Size = 4 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_584	(*((double *) &instData [584]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_568	(*((double *) &instData [568]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_552	(*((double *) &instData [552]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_536	(*((double *) &instData [536]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_520	(*((double *) &instData [520]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_504	(*((double *) &instData [504]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_488	(*((double *) &instData [488]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vpwr_vgnd_472	(*((double *) &instData [472]))	/* Branch Load Group : Size = 8 bytes. */
#define _unconverted_432	(*((double *) &instData [432]))	/* VT_REAL : Size = 8 bytes. */
#define _convertbase_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _vd_128(idx)	(*((double *) &instData [128 + ((idx) * 8)]))	/* VT_REAL : FIXED ARRAY SIZE : Size = 8 bytes. */
#define _i_116	(*((long *) &instData [116]))	/* VT_INT : Size = 4 bytes. */
#define _regvalue_96	(*((double *) &instData [96]))	/* VT_REAL : Size = 8 bytes. */
#define _numbase_72	(*((double *) &instData [72]))	/* VT_REAL : Size = 8 bytes. */
#define _vpwr_60	(*((long *) &instData [60]))	/* VT_NODE : Size = 4 bytes. */
#define _vgnd_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _REG_16	(*((long *) &instData [16]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYSIMSTATICREG_INST_STATIC_H */
