/** 1272019043 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYSIMADCNBIT_INST_STATIC_H
#define DAISYSIMADCNBIT_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_DATA_0__2456	(*((double *) &instData [2456]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_0__2448	(*((double *) &instData [2448]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_0__flow_2432	(*((long *) &instData [2432]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_1__2424	(*((double *) &instData [2424]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_1__2416	(*((double *) &instData [2416]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_1__flow_2400	(*((long *) &instData [2400]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_2__2392	(*((double *) &instData [2392]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_2__2384	(*((double *) &instData [2384]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_2__flow_2368	(*((long *) &instData [2368]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_3__2360	(*((double *) &instData [2360]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_3__2352	(*((double *) &instData [2352]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_3__flow_2336	(*((long *) &instData [2336]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_4__2328	(*((double *) &instData [2328]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_4__2320	(*((double *) &instData [2320]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_4__flow_2304	(*((long *) &instData [2304]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_5__2296	(*((double *) &instData [2296]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_5__2288	(*((double *) &instData [2288]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_5__flow_2272	(*((long *) &instData [2272]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_6__2264	(*((double *) &instData [2264]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_6__2256	(*((double *) &instData [2256]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_6__flow_2240	(*((long *) &instData [2240]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_7__2232	(*((double *) &instData [2232]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_7__2224	(*((double *) &instData [2224]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_7__flow_2208	(*((long *) &instData [2208]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_8__2200	(*((double *) &instData [2200]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_8__2192	(*((double *) &instData [2192]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_8__flow_2176	(*((long *) &instData [2176]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_9__2168	(*((double *) &instData [2168]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_9__2160	(*((double *) &instData [2160]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_9__flow_2144	(*((long *) &instData [2144]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_10__2136	(*((double *) &instData [2136]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_10__2128	(*((double *) &instData [2128]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_10__flow_2112	(*((long *) &instData [2112]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_11__2104	(*((double *) &instData [2104]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_11__2096	(*((double *) &instData [2096]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_11__flow_2080	(*((long *) &instData [2080]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_12__2072	(*((double *) &instData [2072]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_12__2064	(*((double *) &instData [2064]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_12__flow_2048	(*((long *) &instData [2048]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_13__2040	(*((double *) &instData [2040]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_13__2032	(*((double *) &instData [2032]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_13__flow_2016	(*((long *) &instData [2016]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_14__2008	(*((double *) &instData [2008]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_14__2000	(*((double *) &instData [2000]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_14__flow_1984	(*((long *) &instData [1984]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_15__1976	(*((double *) &instData [1976]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_15__1968	(*((double *) &instData [1968]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_15__flow_1952	(*((long *) &instData [1952]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_16__1944	(*((double *) &instData [1944]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_16__1936	(*((double *) &instData [1936]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_16__flow_1920	(*((long *) &instData [1920]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_17__1912	(*((double *) &instData [1912]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_17__1904	(*((double *) &instData [1904]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_17__flow_1888	(*((long *) &instData [1888]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_18__1880	(*((double *) &instData [1880]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_18__1872	(*((double *) &instData [1872]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_18__flow_1856	(*((long *) &instData [1856]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_19__1848	(*((double *) &instData [1848]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_19__1840	(*((double *) &instData [1840]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_19__flow_1824	(*((long *) &instData [1824]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_20__1816	(*((double *) &instData [1816]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_20__1808	(*((double *) &instData [1808]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_20__flow_1792	(*((long *) &instData [1792]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_21__1784	(*((double *) &instData [1784]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_21__1776	(*((double *) &instData [1776]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_21__flow_1760	(*((long *) &instData [1760]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_22__1752	(*((double *) &instData [1752]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_22__1744	(*((double *) &instData [1744]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_22__flow_1728	(*((long *) &instData [1728]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_23__1720	(*((double *) &instData [1720]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_23__1712	(*((double *) &instData [1712]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_23__flow_1696	(*((long *) &instData [1696]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_24__1688	(*((double *) &instData [1688]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_24__1680	(*((double *) &instData [1680]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_24__flow_1664	(*((long *) &instData [1664]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_25__1656	(*((double *) &instData [1656]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_25__1648	(*((double *) &instData [1648]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_25__flow_1632	(*((long *) &instData [1632]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_26__1624	(*((double *) &instData [1624]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_26__1616	(*((double *) &instData [1616]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_26__flow_1600	(*((long *) &instData [1600]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_27__1592	(*((double *) &instData [1592]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_27__1584	(*((double *) &instData [1584]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_27__flow_1568	(*((long *) &instData [1568]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_28__1560	(*((double *) &instData [1560]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_28__1552	(*((double *) &instData [1552]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_28__flow_1536	(*((long *) &instData [1536]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_29__1528	(*((double *) &instData [1528]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_29__1520	(*((double *) &instData [1520]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_29__flow_1504	(*((long *) &instData [1504]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_30__1496	(*((double *) &instData [1496]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_30__1488	(*((double *) &instData [1488]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_30__flow_1472	(*((long *) &instData [1472]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_DATA_31__1464	(*((double *) &instData [1464]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DATA_31__1456	(*((double *) &instData [1456]))	/* Branch Reln : Size = 8 bytes. */
#define _DATA_31__flow_1440	(*((long *) &instData [1440]))	/* Hidden Node : Size = 4 bytes. */
#define _i_1428	(*((long *) &instData [1428]))	/* VT_INT : Size = 4 bytes. */
#define _vd_400(idx)	(*((double *) &instData [400 + ((idx) * 8)]))	/* VT_REAL : FIXED ARRAY SIZE : Size = 8 bytes. */
#define _vref_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _vtrans_clk_328	(*((double *) &instData [328]))	/* VT_REAL : Size = 8 bytes. */
#define _vlogic_low_288	(*((double *) &instData [288]))	/* VT_REAL : Size = 8 bytes. */
#define _approximated_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _FSscale_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _numBits_212	(*((long *) &instData [212]))	/* VT_INT : Size = 4 bytes. */
#define _vLogicHigh_192	(*((double *) &instData [192]))	/* VT_REAL : Size = 8 bytes. */
#define _tRiseFallDel_168	(*((double *) &instData [168]))	/* VT_REAL : Size = 8 bytes. */
#define _vclk_156	(*((long *) &instData [156]))	/* VT_NODE : Size = 4 bytes. */
#define _vin_148	(*((long *) &instData [148]))	/* VT_NODE : Size = 4 bytes. */
#define _DATA_16	(*((long *) &instData [16]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYSIMADCNBIT_INST_STATIC_H */
