function fig = simDACgui()

% (c) jjwikner,MERC


% This should be a file containing the data.
% load DACdatavector DACdatavector
% Further on it will be types (hence fprintf...)
% Typically: set(DACdata,'unit impedance',1e-12) etc.
%% 
%% DACdatavector = ...
%%     [0.1e-18; ... 		    % Gunit = unit conductance
%%     12e-15; ... 		    % Cunit = unit capacitance
%%     1.22e-6; ... 		    % Iunit = unit output current
%%     0; ... 			    % Gpar = avg parasitic conductance
%%     0; ... 			    % Cpar = avg parasitic capacitance
%%     
%%     
%%     sigma   = 0.01;
%% sigma   = 0.0000000000000001;
%% % lite orimliga storlekar pa sigma
%% 
%% Rload   = 50;
%% Gload   = 1/Rload;
%% Cload   = 50e-9;
%%  				    
%% 	
%%     ];
%%     
%% Gunit = DACdatavector(1);

wndwid = 0.65;
wndhgt = 0.9;
btnwid = 0.20; btnwid = wndwid/3;
btnhgt = 0.03; btnhgt = wndhgt/35;
btnspcX = btnwid*1.5;
btnspcY = btnhgt*2;
Xstart = 0.03;
Ystart = 0.03; % this should be larger than (or equal to) btnhgt
frmhgt = 0.4;
frmwid = (1-4*Xstart)/2;
F1startY = Ystart+btnhgt+btnspcY;
F2startY = (1-Ystart-frmhgt);
frmclr = [0.2 0.8 0.8];
bkgclr = [0.7 0.8 0.8];

FileName = 'C:\My Documents\jacob\matlab\DAC\simDACgui.m';


% Main Simulation Window 

h0 = figure('Units','normalized', ...
   'Color',bkgclr, ...
   'Name', 'DAC Main Simulation Window', ...
   'NumberTitle', 'off', ... 
   'PaperType','A4', ...
   'PaperOrientation', 'landscape', ...
   'FileName',FileName, ...
	'PaperUnits','normalized', ...
	'PaperPosition',[0.17971 0.029823 0.64057 0.94035], ...
	'Position',[0.340 0.03 wndwid wndhgt], ...
	'Tag','DAC Main Simulation Window', ...
   'ToolBar','none');

% Frame for the impedance relations

h1 = uicontrol('Parent',h0, ...
   'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F2startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart 1-Ystart frmwid btnhgt], ...
   'Style','text', ...
   'String','Impedance relations', ...
   'Tag','StaticText1');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit conductance', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Load conductance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','Load capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-5*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Parasitic conductance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-5*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-6*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Parasitic capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-6*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F2startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Include parasitics',...
	'Tag','Checkbox1');

% Frame for component matching relations

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart+0.5 F2startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame2');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart+0.5 1-Ystart frmwid btnhgt], ...
   'Style','text', ...
   'String','Matching relations', ...
   'Tag','StaticText2');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit std. dev. ', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 1-Ystart-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','X gradient', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth 1-Ystart-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 1-Ystart-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Y gradient', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth 1-Ystart-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 1-Ystart-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','Number of samples', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth 1-Ystart-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart+0.5 F2startY+Ystart+2*btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Plot and Save Histograms',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart+0.5 F2startY+Ystart+btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Include stochastic',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart+0.5 F2startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
    'Value',1, ...
  'String','Include gradients',...
	'Tag','Checkbox1');

% Frame for DAC architecture

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F1startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame3');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F1startY+frmhgt frmwid btnhgt], ...
   'Style','text', ...
   'String','DAC Architecture', ...
   'Tag','StaticText3');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Number of bits', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Segmentation', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Oversampling ratio', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','IP filter type and order', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-5*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Modulator type and order', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-5*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F1startY+Ystart+btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Differential output signal',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F1startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Blaha blaha',...
	'Tag','Checkbox1');



% Frame for simulation options

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart+0.5 F1startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame3');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart+0.5 F1startY+frmhgt frmwid btnhgt], ...
   'Style','text', ...
   'String','Simulator options', ...
   'Tag','StaticText3');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Number of samples', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Sample Frequency', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Tones', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart+0.5 F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','Amplitude levels', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[1-2*Xstart-swidth F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart+0.5 F1startY+Ystart+2*btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Plot and Save Output Spectra',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart+0.5 F1startY+Ystart+btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Plot and Save SFDR',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart+0.5 F1startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
    'Value',1, ...
  'String','Plot and Save SNDR',...
	'Tag','Checkbox1');

% Organization buttons


h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.3 0.1], ...
	'Callback','simDAC(''run'')', ...
	'ListboxTop',0, ...
	'Position',[Xstart Ystart btnwid btnhgt], ...
	'String','Run Simulator', ...
   'Tag','Pushbutton1');

sspace = (1-2*Xstart-4*btnwid)/6;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.4 0.8 0.3], ...
	'Callback','simDAC(''help'')', ...
	'ListboxTop',0, ...
	'Position',[0.5-btnwid-sspace Ystart btnwid btnhgt], ...
	'String','Help', ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.1 0.4 0.8], ...
	'Callback','simDAC(''default'')', ...
	'ListboxTop',0, ...
	'Position',[0.5+sspace Ystart btnwid btnhgt], ...
	'String','Defaults', ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.8 0.7], ...
	'Callback','simDAC(''quit'')', ...
	'ListboxTop',0, ...
	'Position',[1-Xstart-btnwid Ystart btnwid btnhgt], ...
	'String','Quit Simulator', ...
   'Tag','Pushbutton1');

% ================================
% Sweep Analyses Simulation Window 
% ================================

wndwid = wndwid/2;
btnwid = 0.25; 
btnspcX = btnwid*1.5;
frmhgt = 0.4;
frmwid = (1-2*Xstart);
frmclr = [0.3 0.8 0.9];
bkgclr = [0.9 0.8 0.8];

h0 = figure('Units','normalized', ...
   'Color',bkgclr, ...
   'Name', 'Sweep Analyses Window', ...
   'NumberTitle', 'off', ... 
   'PaperType','A4', ...
   'PaperOrientation', 'landscape', ...
   'FileName',FileName, ...
	'PaperUnits','normalized', ...
	'PaperPosition',[0.33986 0.029823 0.32029 0.94035], ...
	'Position',[0.01 0.03 wndwid wndhgt], ...
	'Tag','Sweep Analyses Window', ...
   'ToolBar','none');

% Frame for impedance relations

h1 = uicontrol('Parent',h0, ...
   'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F2startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart 1-Ystart frmwid btnhgt], ...
   'Style','text', ...
   'String','Impedance sweeps', ...
   'Tag','StaticText1');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit conductance', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Load conductance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','Load capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-5*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Parasitic conductance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-5*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-6*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Parasitic capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-6*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F2startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Include parasitics',...
	'Tag','Checkbox1');

% Frame for matching

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F1startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame3');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F1startY+frmhgt frmwid btnhgt], ...
   'Style','text', ...
   'String','Matching sweeps', ...
   'Tag','StaticText3');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Number of bits', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Segmentation', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Oversampling ratio', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','IP filter type and order', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-5*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Modulator type and order', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-5*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F1startY+Ystart+btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Differential output signal',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F1startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Blaha blaha',...
	'Tag','Checkbox1');


% Organization buttons

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.3 0.1], ...
	'Callback','simDAC(''run'')', ...
	'ListboxTop',0, ...
	'Position',[Xstart Ystart btnwid btnhgt], ...
	'String','Run Sweep', ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.4 0.8 0.3], ...
	'Callback','simDAC(''help'')', ...
	'ListboxTop',0, ...
	'Position',[0.5-btnwid/2 Ystart btnwid btnhgt], ...
	'String','Help', ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.1 0.4 0.8], ...
	'Callback','simDAC(''default'')', ...
	'ListboxTop',0, ...
	'Position',[1-Xstart-btnwid Ystart btnwid btnhgt], ...
	'String','Defaults', ...
   'Tag','Pushbutton1');

% ================================
% DAC Architecture Window 
% ================================

btnwid = 0.25; 
btnspcX = btnwid*1.5;
frmhgt = 0.4;
frmwid = (1-2*Xstart);
frmclr = [0.5 0.6 0.9];
bkgclr = [0.9 0.9 0.8];

h0 = figure('Units','normalized', ...
   'Color',bkgclr, ...
   'Name', 'Sweep Analyses Window', ...
   'NumberTitle', 'off', ... 
   'PaperType','A4', ...
   'PaperOrientation', 'landscape', ...
   'FileName',FileName, ...
	'PaperUnits','normalized', ...
	'PaperPosition',[0.33986 0.029823 0.32029 0.94035], ...
	'Position',[0.221 0.03 wndwid wndhgt], ...
	'Tag','Sweep Analyses Window', ...
   'ToolBar','none');

% Frame for impedance relations

h1 = uicontrol('Parent',h0, ...
   'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F2startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart 1-Ystart frmwid btnhgt], ...
   'Style','text', ...
   'String','Impedance sweeps', ...
   'Tag','StaticText1');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit conductance', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Unit capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Load conductance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','Load capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-5*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Parasitic conductance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-5*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart 1-Ystart-6*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Parasitic capacitance', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth 1-Ystart-6*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F2startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Include parasitics',...
	'Tag','Checkbox1');

% Frame for matching

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F1startY frmwid frmhgt], ...
	'Style','frame', ...
   'Tag','Frame3');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[Xstart F1startY+frmhgt frmwid btnhgt], ...
   'Style','text', ...
   'String','Matching sweeps', ...
   'Tag','StaticText3');

swidth = (frmwid - 2.5*Xstart)/2;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Number of bits', ...
   'Tag','StaticText1');

gout = 1e-12;

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-btnspcY swidth btnhgt], ...
   'Style','edit', ...
   'String',num2str(gout),...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Segmentation', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-2*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Oversampling ratio', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-3*btnspcY swidth btnhgt], ...
   'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
   'Style','text', ...
  'String','IP filter type and order', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-4*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',frmclr, ...
	'ListboxTop',0, ...
	'Position',[2*Xstart F1startY+frmhgt-5*btnspcY swidth btnhgt], ...
   'Style','text', ...
   'String','Modulator type and order', ...
   'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[frmwid-swidth F1startY+frmhgt-5*btnspcY swidth btnhgt], ...
    'String',num2str(gout),...
	'Style','edit', ...
   'Tag','EditText1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F1startY+Ystart+btnspcY frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Differential output signal',...
	'Tag','Checkbox1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'ListboxTop',0, ...
	'BackgroundColor',bkgclr, ...
	'Position',[2*Xstart F1startY+Ystart frmwid-2*Xstart btnhgt], ...
   'Style','checkbox', ...
   'Value',1, ...
   'String','Blaha blaha',...
	'Tag','Checkbox1');


% Organization buttons

h1 = uicontrol('Parent',h0, ...
   'Units','normalized', ...
   'BackgroundColor',bkgclr, ...
	'ListboxTop',0, ...
	'Position',[0.8*Xstart Ystart*0.9 btnwid+0.4*Xstart btnhgt+0.2*Ystart], ...
	'Style','frame', ...
   'Tag','Frame1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.3 0.1], ...
	'Callback','simDAC(''run'')', ...
	'ListboxTop',0, ...
	'Position',[Xstart Ystart btnwid btnhgt], ...
	'String','Update DAC', ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.4 0.8 0.3], ...
	'Callback','simDAC(''help'')', ...
	'ListboxTop',0, ...
	'Position',[0.5-btnwid/2 Ystart btnwid btnhgt], ...
	'String','Help', ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.1 0.4 0.8], ...
	'Callback','simDAC(''default'')', ...
	'ListboxTop',0, ...
	'Position',[1-Xstart-btnwid Ystart btnwid btnhgt], ...
	'String','Defaults', ...
   'Tag','Pushbutton1');
