/** 4274765733 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYSIMDAC_INST_STATIC_H
#define DAISYSIMDAC_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_vout_208	(*((double *) &instData [208]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vout_200	(*((double *) &instData [200]))	/* Branch Reln : Size = 8 bytes. */
#define _vout_flow_188	(*((long *) &instData [188]))	/* Hidden Node : Size = 4 bytes. */
#define _vref_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _outScaled_112	(*((double *) &instData [112]))	/* VT_REAL : Size = 8 bytes. */
#define _vLogicHigh_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _tRiseFallDel_64	(*((double *) &instData [64]))	/* VT_REAL : Size = 8 bytes. */
#define _vout_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _DATA_16	(*((long *) &instData [16]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYSIMDAC_INST_STATIC_H */
