(put 'ad_funs 'symbol-type "floor planning fun")
(setq ad_funs '(
("adpBlockAnalysis" "l_blockInstances")
("adpBlockAnalysisReport" "l_blockInstances t_fileName")
("adpCheckRgnOverlap" "d_cv [l_regions]")
("adpChipAnalysis" "d_cv")
("adpChipAnalysisReport" "d_cv t_fileName")
("adpGroupAnalysis" "l_groups")
("adpGroupAnalysisReport" "l_groups t_fileName")
("adpGroupAreaEst" "d_groupId")
("adpHierGen" "t_libName t_cellName t_viewName t_versionName")
("adpIORandomPlaceGE" "d_cv")
("adpInitFloorplan" "d_cv t_engine [?all g_all t ?design g_design t ?rgn g_region t ?grp g_group t ?grid g_grid t ?status g_status t ?sRoute g_specialRoute t ?froute g_finalRoute t ?prsvIO g_preserveIOcell nil ?prsvMacro g_preserveStdCell nil ?prsvMacro g_preserveMacro nil ?array t_array "" ?sdFile t_sdfFileName "" ?fpFile t_floorplanFileName "" ?origin t_origin "center" ?aspr f_aspectRatio 1.0 ?X f_Xdimension 0.0 ?Y f_Ydimension 0.0 ?coreUtil f_coreUtil 0.8 ?rowUtil f_rowUtil 0.9 ?iotc f_iotc 0.0 ?createRow g_createRow nil ?flipRow g_flipRow nil ]")
("adpPartition" "d_libId d_cv x_num x_r1 x_r2 x_ppnIgnore l_criticality l_path l_weights t_create t_prefix t_pinType l_subjects x_dump") 
("adpRegionAnalysis" "l_regions")	
("adpRegionAnalysisReport" "l_regions t_fileName")
("adpSimpleAreaEst" "d_cv [f_coreU] [f_AR] [f_rowU] [f_iotc]")
("adpfpCheckInstOverlap" "d_cv [l_InstId] [g_full]")
("adphmBreakBlock" "d_BlockInstanceId")
("adphmCreateBlock" "d_BlockInstanceId l_instIds t_pinDevName")
("adppaEstNetDelay" "d_cv t_tblName l_hLayer l_vLayer d_nets x_estMode t_hier t_allHierNet t_rcOnly")
("adppaEstPathDelay" "d_cv t_tblName l_hLayer l_vLayer d_paths X_estMode t_hier")
("adppaGenRCReport" "d_cv t_fileName l_nets")
("adppaGenRSPF" "d_cv t_fileName l_nets t_map t_allHierNet")
("adppaGenSDF" "d_cv t_fileName l_nets t_map t_allHierNet")
("adppaLoadSDF" "d_cv t_fileName g_overWrite x_weight")
))
