(put 'cd_funs 'symbol-type "component descr format fun")
(setq cd_funs '(
("cdfCopyCDF" "d_id t_dataType g_dataId" "Copies CDF data onto the specified id, creating a new dataId of the specified type.")
("cdfCopyParam" "g_dataId g_paramId" "Copies a parameter, adding it to the dataId.")
("cdfCreateBaseCellCDF" "d_cellId [?doneProc t_doneProc t_formInitProc]" "Creates a base-level CDF for a cell.")
("cdfCreateBaseLibCDF" "d_libId [?doneProc t_doneProc t_formInitProc]" "Creates a base-level CDF for a library.")
("cdfCreateParam" "g_cdfDataId ?name t_name ?type t_type [?defValue g_defValue] [?units t_units] [?parseAsNumber t_parseAsNumber] [?choices t_choices] [?prompt t_prompt] [?use t_use] [?display t_display] [?editable t_editable] [?dontSave t_dontSave] [?callback t_callback] [?storeDefault t_storeDefault] [?parseAsCEL t_parseAsCEL]" "Creates a parameter on the specified cdfDataId with the specified attributes.")
("cdfCreateUserCellCDF" "d_cellId [?doneProc t_doneProc t_formInitProc]" "Creates a user-level CDF for a cell.")
("cdfCreateUserLibCDF" "d_libId [?doneProc t_doneProc t_formInitProc]" "Creates a user-level CDF for a library.")
("cdfDeleteCDF" "g_cdfDataId" "Deletes a CDF description, including all attached parameters.")
("cdfDeleteParam" "g_cdfParamId" "Deletes a CDF parameter.")
("cdfGetBaseCellCDF" "d_cellId" "Returns the base-level CDF attached to a cell.")
("cdfGetBaseLibCDF" "d_libId" "Returns the base-level CDF attached to a library.")
("cdfGetCellCDF" "d_lcellId" "Returns the effective CDF attached to a cell.")
("cdfGetInstCDF" "d_instId" "Returns the effective CDF associated with an instance.")
("cdfGetLibCDF" "d_libId" "Returns the effective CDF attached to a library.")
("cdfGetUserCellCDF" "d_cellId" "Returns the user-level CDF attached to a cell.")
("cdfGetUserLibCDF" "d_libId" "Returns the user-level CDF attached to a library.")
("cdfSaveCDF" "g_cdfDataId" "Saves a CDF description to disk.")
))
