(put 'cw_funs 'symbol-type "cadence waves fun")
(setq cw_funs '(
("cwAddGroup" "w_windowId t_groupName")
("cwAddSignal" "w_windowId t_signalName t_fullPathFileName t_shmServerName")
("cwCloseDatabase" "w_windowId t_fullPathFileName t_shmServerName")
("cwCollapseBusStrip" "w_windowId x_stripId")
("cwCopy" "w_windowId")
("cwCreateGroup" "w_windowId t_groupName")
("cwCreateMarker" "w_windowId t_markerName x_visible f_time x_timeScale")
("cwCreateRestoreFile" "w_windowId t_filePath t_fileName")
("cwCut" "w_windowId")
("cwDeleteGroup" "w_windowId t_groupName")
("cwDeleteMarker" "w_windowId t_markerName")
("cwExpandBusStrip" "w_windowId x_stripId")
("cwGetCurrentTime" "w_windowId")
("cwGetMarkerList" "w_windowId")
("cwGetSelectedMarkers" "w_windowId")
("cwJumpToTime" "w_windowId f_time x_timeScale")
("cwOpenDatabase" "w_windowId t_fullPathFileName t_shmServerName")
("cwPanLeft" "w_windowId")
("cwPanRight" "w_windowId")
("cwPaste" "w_windowId")
("cwRedrawWin" "w_windowId")
("cwRestoreWaveEnv" "w_windowId t_filePath t_fileName")
("cwScrollDown" "w_windowId")
("cwScrollToStrip" "w_windowId x_stripIndex")
("cwScrollUp" "w_windowId")
("cwSelectDatabase" "w_windowId t_fullPathFileName t_shmServerName")
("cwSelectGroup" "w_windowId t_groupNum")
("cwSelectMarker" "w_windowId t_markerNum")
("cwSelectSignal" "w_windowId t_signalName t_fullPathFileName t_shmServerName")
("cwSelectStrip" "w_windowId x_stripIndex")
("cwSetBaseline" "w_windowId f_time x_timeScale")
("cwSetCurrentDatabase" "w_windowId t_fullPathFileName t_shmServerName")
("cwSetGridSignal" "w_windowId t_signalName t_fullPathFileName t_shmServerName")
("cwSetGridType" "w_windowId x_grid")
("cwSetNumStrips" "w_windowId x_numStrips")
("cwSetRadix" "w_windowId x_radix")
("cwSetScope" "w_windowId t_scopeName")
("cwSetSigScrollMode" "w_windowId x_scrollMode")
("cwSetSigScrollNum" "w_windowId x_numToScroll")
("cwSetSigScrollPercent" "w_windowId f_percent")
("cwSetTimeJust" "w_windowId x_just")
("cwSetTimeScale" "w_windowId x_scaleType")
("cwSetTimeScrollInterval" "w_windowId x_interval")
("cwSetTimeScrollMode" "w_windowId x_scrollMode")
("cwSetTimeScrollPercent" "w_windowId x_percent")
("cwSetTimeScrollSignal" "w_windowId t_signal t_fullPathFileName t_shmServerName")
("cwSetWriterMode" "w_windowId x_modeType")
("cwSetZoomScales" "w_windowId f_zoomInScaleFactor f_zoomOutScaleFactor")
("cwUnselectAll" "w_windowId")
("cwViewBaseline" "w_windowId")
("cwViewCursor" "w_windowId")
("cwViewGrid" "w_windowId")
("cwViewGroup" "w_windowId t_groupNum")
("cwViewMarker" "w_windowId t_markerNum")
("cwViewMarkerRange" "w_windowId x_markerNum x_markerNum")
("cwZoomIn" "w_windowId")
("cwZoomOut" "w_windowId")
("cwZoomRange" "w_windowId")
))
