(put 'da_funs 'symbol-type "graph browser fun")
(setq da_funs '(
("dagAddActionToObject" "l_action w_object" "Adds an action to a specified dag (directed acyclic graph) node or class.")
("dagCreateClass" "t_className" "Creates a dag class and returns it.")
("dagCreateNode" "t_nodeName w_class" "Creates a dag node and returns it.")
("dagDeleteActionFromObject" "t_actionName w_object" "Deletes an action from a dag class or node.")
("dagDestroyNode" "w_node" "Destroys a dag node. Also destroys all descendant nodes and arcs of this node, as well as the arcs linking this node to its parent(s).")
("dagDisplayTool" "[w_dagTool] [g_runPlacer]" "Redisplays a dag tool.")
("dagGetCurrentObject" "" "Returns the current dag node.")
("dagGetCurrentTool" "" "Returns the current dag tool.")
("dagLinkParentToChild" "w_parent w_child" "Creates a dag arc that links a parent node to a child node.")
("dagNumToTool" "x_toolNumber" "Returns the dag tool that matches the window number specified by x_toolNumber.")
("dagOpenTool" "x_backGroundColor l_bBox w_startingObject t_name t_help" "Creates a dag tool object and opens a window in which to display the graph.")
("dagPopTool" "w_dagTool" "Pops a tool stack.")
("dagPushTool" "w_dagTool w_newStartingNode" "Pushes a new starting object onto the tool stack.")
("dagRefreshObject" "w_dagNode" "Redraws a node in all the tools it is currently displayed in.")
("dagSetActionStatus" "t_actionName w_dagObject g_status" "Sets the status of an action in the action list of a dag class or node.")
("dagSetCurrentTool" "w_dagTool" "Sets the current dag tool.")
("dagSetExpandedActionStatus" "t_actionName w_dagObject g_status" "Sets the status of an action in the expanded action list of a node.")
("dagSetFont" "t_XFontName" "Modifies the font used in text mode in any dag tool.")
("dagUnlinkParentFromChild" "w_arc" "Removes the link between a parent node and a child node.")
))
