(put 'de_funs 'symbol-type "design editor fun")
(setq de_funs '(
("deCopy" "[w_window [g_winSpec]]")
("deDisableApp" "w_window t_appName")
("deEditInPlace" "w_window [l_fileSpec [t_accessMode [t_appName]]]")
("deEnableApp" "w_window t_appName")
("deGetAllRootTypes" "")
("deGetAllViewTypes" "")
("deGetAppInfo" "t_viewType")
("deGetCellView" "[w_window [x_level]]")
("deGetContext" "[w_window [x_level]]")
("deGetEIP" "[w_window [x_level]]")
("deGetEditCellView" "[w_window]")
("deGetEditContext" "[w_window]")
("deGetEditLevel" "[w_window]")
("deGetEditRootType" "[w_window]")
("deGetEditViewType" "w_window")
("deGetMaxEditLevel" "[w_window]")
("deGetProbeContext" "[w_window]")
("deGetProbeTrigger" "")
("deGetPushed" "[w_window [x_level]]")
("deGetRootType" "[w_window [x_level]]")
("deGetViewType" "w_window [x_level]")
("deInheritEnabling" "t_viewType")
("deInheritMenus" "t_viewType")
("deInstallApp" "w_window t_appName")
("deIsCDBA" "d_cellview")
("deOpen" "[l_fileSpec [g_winSpec [t_accessMode [t_appName]]]]")
("dePush" "[l_fileSpec [g_winSpec [t_accessMode [t_appName]]]]")
("deRegApp" "?viewType t_viewType ?parentType t_parentType ?appName t_appName ?help t_help ?dataTrigger s_dataTrigger ?appTrigger s_appTrigger ?enableTrigger s_enableTrigger ?menuTrigger s_menuTrigger ?postInstallTrigger s_postInstallTrigger ?widgetType t_widgetType ?noCadenceMenu g_noCadenceMenu ?appTitle t_appTitle")
("deRegProbeTrigger" "s_probeTrigger")
("deRegUserTriggers" "t_viewType [s_appTrigger [s_menuTrigger [s_postInstallTrigger]]]")
("deReturn" "[w_window [x_level]]")
("deSetCellView" "[w_window [d_cellview [x_level]]]")
("deSetContext" "[w_window [g_context [x_level]]]")
("deSetProbeContext" "[w_window [g_probeContext]]")
("deSwap" "[l_fileSpec [g_winSpec [t_accessMode [t_appName]]]]")
("deUnInheritEnabling" "t_viewType")
("deUnInheritMenus" "t_viewType")
("deUnRegApp" "t_viewType")
("deUnRegProbeTrigger" "")
("deUnRegUserTriggers" "t_viewType")
("deViewTypeIsRegistered" "t_viewType")
))
