(put 'df_funs 'symbol-type "design flow fun")
(setq df_funs '(
("dfAddStepToFlowchart" "?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName ?step g_step ?stepName t_stepName [?nameExt t_nameExt] ?xy l_point " "Adds a step to a flowchart.")
("dfCheckProperties" "?step g_step ?stepInst g_stepInst ?flowchart g_flowchart ?flowchartInst g_flowchartInst " "Checks the validity of the properties on a Design Flow object (design step, step instance, flowchart, or flowchart instance).")
("dfCloseFlowchart" "?flowchart g_flowchart ?libName t_libName ?name t_name " "Closes a flowchart and all flowchart instances instantiated from it.")
("dfCloseFlowchartInst" "?flowchartInst g_flowchartInst ?libName t_libName ?cellName t_cellName ?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName " "Closes a flowchart instance.")
("dfCreateFlowchart" "?name t_name ?libName t_libName [?size l_size] [?lowerLeft l_lowerLeft] [?arcPen x_arcPen] " "Creates an empty flowchart.")
("dfDeleteStepFromFlowchart" "?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName ?step g_step ?stepName t_stepName [?nameExt t_nameExt] " "Deletes a step from a flowchart.")
("dfDisplayFlowchart" "?flowchartInst g_flowchartInst ?libName t_libName ?cellName t_cellName ?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName [?size l_size] [?lowerLeft l_lowerLeft] [?dagTool w_dagTool] " "Creates a new window and displays a flowchart instance in it.")
("dfDisplaySubflowchart" "?stepInst g_stepInst " "Displays the subflowchart attached to a step instance.")
("dfEncapsulate" "?name t_name [?useForm t/nil] [?inputFiles l_inputFiles] [?outputFiles l_outputFiles] [?requiredInfo l_requiredInfo] [?formInfo l_formInfo] [?exportInfo l_exportInfo] [?importInfo l_importInfo] [?description t_description] [?help t_help] [?function s_function] [?preFunc s_preFunc] [?postFunc s_postFunc] [?autoRunPostFunc t/nil] [?triggerFunc s_triggerFunc] [?errorFunc s_errorFunc] [?resetFunc s_resetFunc] [?highlightFunc s_highlightFunc] [?unhighlightFunc s_unhighlightFunc] [?okToRunFunc s_okToRunFunc] [?displayList w_displayList] [?skillObject t_skillObject] [?subflowchartName t_subflowchartName] [?subflowchartLibName t_subflowchartLibName] [?switchBox t/nil] [?disableSwitchBoxFormField t/nil] " "Defines a new design step. Each of the optional parameters represents a property associated with the design step.")
("dfGetChildStepInsts" "?stepInst g_stepInst " "Returns a list of step instances that are the children of stepInst.")
("dfGetChildSteps" "?step g_step ?stepName t_stepName ?flowchart g_flowchart [?nameExt t_nameExt] " "Returns a list of steps that are the children of step on flowchart.")
("dfGetCurrentFlowchart" "" "Returns the active flowchart.")
("dfGetCurrentFlowchartInst" "" "Returns the flowchart instance in the active dag tool.")
("dfGetCurrentStep" "" "Returns the current design step.")
("dfGetCurrentStepInst" "" "Returns the active design step instance.")
("dfGetCycleEntryParents" "?stepInst g_stepInst " "Returns the parents of a cycle entry point.")
("dfGetDependency" "?stepInst g_stepInst ?step g_step ?flowchart g_flowchart [?nameExt t_nameExt] " "Returns the dependency in a step instance or step on a flowchart.")
("dfGetFinishedParents" "?stepInst g_stepInst " "Returns a list of the step instances that are the parents of stepInst and have been finished successfully.")
("dfGetFlowchart" "?libName t_libName ?name t_name " "Returns a flowchart.")
("dfGetFlowchartInst" "?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName ?libName t_libName ?cellName t_cellName " "Returns a flowchart instance.")
("dfGetFlowchartInstList" "g_flowchart " "Returns a list of flowchart instances instantiated from a flowchart.")
("dfGetFlowchartList" "" "Returns a list of all flowcharts created in the current design session.")
("dfGetLockedPropList" "g_object " "Returns a list of locked properties on a Design Flow object.")
("dfGetParentStepInsts" "?stepInst g_stepInst " "Returns a list of step instances that are the parents of stepInst.")
("dfGetParentSteps" "?step g_step ?stepName t_stepName ?flowchart g_flowchart [?nameExt t_nameExt] " "Returns a list of steps that are the parents of step on flowchart.")
("dfGetStep" "?name t_name " "Returns a design step.")
("dfGetStepInst" "?step g_step ?stepName t_stepName ?flowchartInst g_flowchartInst ?cellName t_cellName ?libName t_libName ?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName [?nameExt t_nameExt] " "Returns a design step instance.")
("dfGetStepInstList" "g_step [g_flowchartInst] " "Returns a list of design step instances instantiated from the step g_step.")
("dfGetStepInstListOnFlowchartInst" "g_flowchartInst " "Returns a list of all step instances on a flowchart instance.")
("dfGetStepList" "" "Returns a list of all design steps created in the current design session.")
("dfGetStepNode" "?step g_step [?nameExt t_nameExt] ?flowchart g_flowchart " "Returns the node identified by a design step, its extension, and the flowchart to which it is added.")
("dfGetStepNodeList" "g_step g_flowchart " "Returns a list of dag nodes created from a step on a flowchart.")
("dfGetSwitchStepInst" "?stepInst g_stepInst " "Returns the step instance for the switch box to switch to.")
("dfGetUnfinishedParents" "?stepInst g_stepInst " "Returns a list of the step instances that are the parents of stepInst and have not been finished yet.")
("dfIsPropLocked" "g_object s_prop " "Finds out if a property is locked.")
("dfIsSwitchBox" "?stepInst g_stepInst " "Tells you whether the designated instance is a switch box.")
("dfLinkFlowchartSteps" "?flowchart g_flowchart ?parent g_parentStep ?parentName t_parentName [?parentNameExt t_parentNameExt] ?child g_childStep ?childName t_childName [?childNameExt t_childNameExt] [?cycleEntry t/nil] [?pointList l_pointList] [?arcPen x_arcPen] " "Establishes a parent-child relationship between two design steps on a flowchart.")
("dfLockProp" "g_object sl_prop " "Locks a property assigned to any Design Flow object (design step, step instance, flowchart, or flowchart instance).")
("dfOpenFlowchart" "?libName t_libName ?name t_name " "Opens a flowchart.")
("dfOpenFlowchartInst" "?libName t_libName ?cellName t_cellName ?flowchart g_flowchart ?flowchartName t_flowchartName ?flowchartLibName t_flowchartLibName " "Opens a flowchart instance.")
("dfRefreshFlowchartInst" "g_flowchartInst " "Redisplays a flowchart instance.")
("dfRefreshStepInst" "?stepInst g_stepInst " "Refreshes a step instance.")
("dfResetRunTimeProps" "?stepInst g_stepInst " "Resets all run-time properties (running, finished, failMsg, stage, and result) in a step instance to nil.")
("dfResetStepInst" "?stepInst g_stepInst " "Calls dfResetRunTimeProps, then refreshes either the step instance or the flowchart instance it is in.")
("dfRunPostFunc" "?stepInst g_stepInst " "Evaluates stepInst->step->postFunc if it is defined.")
("dfRunStepInst" "[?stepInst g_stepInst] " "Invokes and controls a design step instance and provides the mechanism to run a design step.")
("dfSaveFlowchart" "?flowchart g_flowchart ?logMessage t_logMessage " "Saves a flowchart.")
("dfSaveFlowchartInst" "?flowchartInst g_flowchartInst ?logMessage t_logMessage " "Saves a flowchart instance.")
("dfSelectSwitch" "?stepInst g_stepInst ?switchStepInst g_switchStepInst ?switchName t_switchName [?switchNameExt t_switchNameExt] " "Enables a switch choice.")
("dfSetCycleEntryParent" "?step g_step [?nameExt t_nameExt] ?parent g_parent [?parentNameExt g_parentNameExt] ?flowchart g_flowchart " "Designates the cycle entry point (step) and its parent (parent).")
("dfSetDependency" "?step g_step ?flowchart g_flowchart ?dependency s_dependency [?nameExt t_nameExt] " "Assigns a dependency to a step on a flowchart.")
("dfSetPens" "g_libId " "Links Design Flow layers to the pen table of the default display list defined in the technology file.")
("dfSetSwitchBox" "?step g_step [?displayList g_displayList] [?skillObject t_skillObject] [?function s_function] " "Makes a design step a switch box.")
("dfViewProps" "[?step g_step] [?stepInst g_stepInst] " "Opens a view file window with a list of the properties attached to a step or step instance.")
("dfViewProps" "[?flowchart g_flowchart] [?flowchartInst g_flowchartInst] " "Opens a window with a list of the properties that are attached to a flowchart or flowchart instance.")
))
