(put 'dl_funs 'symbol-type "display list fun")
(setq dl_funs '(
("dlAddArc" "w_dlist x_penNumber l_point1 l_point2 n_startAngle n_sweepAngle [s_tagSymbol]" "Adds an arc to a display list.")
("dlAddBox" "w_dlist x_penNumber l_point1 l_point2 [s_tagSymbol]" "Adds a box to a display list.")
("dlAddCircle" "w_dlist x_penNumber l_point x_radius [s_tagSymbol]" "Adds a circle to a display list.")
("dlAddDonut" "w_dlist x_penNumber l_point x_innerRadius x_outerRadius [s_tagSymbol]" "Adds a donut (two concentric circles) to a display list.")
("dlAddEventObject" "w_dlist l_point1 l_point2 t_procName t_procArgs [t_highlightMode] [g_doesGraphics] [s_tagSymbol]" "Adds an event object to a display list. An event object is a SKILL procedure called whenever the user presses a mouse button or a keyboard key.")
("dlAddPath" "w_dlist x_penNumber x_pathWidth t_pathEndType l_pointsList [s_tagSymbol]" "Adds a path to a display list.")
("dlAddPoint" "w_dlist x_penNumber l_point [s_tagSymbol]" "Adds a point to a display list.")
("dlAddPolygon" "w_dlist x_penNumber l_pointsList [s_tagSymbol]" "Adds a polygon to a display list.")
("dlAddRasterText" "w_dlist x_penNumber l_point t_text t_fontName [t_verticalJustify] [t_horizontalJustify] [s_tagSymbol]" "Adds a text string to a display list.")
("dlAddSegment" "w_dlist x_penNumber l_point1 l_point2 [s_tagSymbol]" "Adds a line segment to a display list.")
("dlAddSkillObject" "w_dlist x_penNumber l_point1 l_point2 t_procName t_procArgs [s_tagSymbol]" "Adds a SKILL object to a display list. A SKILL object is a SKILL procedure called whenever the object is drawn.")
("dlAddStrokeText" "w_dlist x_penNumber l_point t_text t_justification t_fontName x_height [t_orientation] [g_drafting] [s_tagSymbol]" "Adds a stroke text string to a display list.")
("dlAttachDlistToWidget" "w_displayList x_widgetId" "Attaches a display list to a widget.")
("dlAttachDlistToWindow" "w_displayList w_windowId" "Attaches a display list to a window.")
("dlClearDisplayList" "w_displayList" "Removes all the objects from a display list.")
("dlCloseWidget" "x_widgetId" "Closes (destroys) a widget.")
("dlConfigureButton" "x_button x_xPosition x_yPosition x_width x_height" "Moves a button.")
("dlDetachDlistFromWidget" "w_displayList x_widgetId" "Detaches a display list from a widget.")
("dlDetachDlistFromWindow" "w_displayList w_windowId" "Detaches a display list from a window.")
("dlDisplay" "w_displayList" "Redraws the display list in all the windows and buttons it is currently attached to.")
("dlDlistToIcon" "w_displayList x_width x_height [x_backColorIndex]" "Converts a display list to an icon.")
("dlDrawArc" "l_point1 l_point2 f_startAngle f_sweepAngle" "Draws an arc to the screen from within a SkillObject procedure.")
("dlDrawBox" "l_point1 l_point2" "Draws a box to the screen from within a SkillObject procedure.")
("dlDrawCircle" "l_point x_radius" "Draws a circle to the screen from within a SkillObject procedure.")
("dlDrawDonut" "l_point x_innerRadius x_outerRadius" "Draws a donut to the screen from within a SkillObject procedure.")
("dlDrawPath" "x_pathWidth t_pathEndType l_pointsList" "Draws a path to the screen from within a SkillObject procedure.")
("dlDrawPoint" "l_point" "Draws a point to the screen from within a SkillObject procedure.")
("dlDrawPolygon" "l_pointsList" "Draws a polygon to the screen from within a SkillObject procedure.")
("dlDrawRasterText" "l_point t_text t_fontName [t_verticalJustify] [t_horizontalJustify]" "Draws a text string to the screen from within a SkillObject procedure.")
("dlDrawSegment" "l_point1 l_point2" "Draws a line segment to the screen from within a SkillObject procedure.")
("dlDrawStrokeText" "l_point t_text t_justification t_fontName x_height t_orientation" "Draws a stroke text string to the screen from within a SkillObject procedure.")
("dlEnableItem" "w_dlist x_penNumber s_symbolTag g_enableOrDisable" "Allows you to turn on or off shapes within a display list that match a symbol.")
("dlFitDlistOnDraw" "w_displayList x_widgetId g_doFit" "Specifies whether a display list should automatically fit within a widget.")
("dlMakeDisplayList" "" "Creates an empty display list that you can add objects to.")
("dlMakeDlistButton" "x_parentWidgetId x_xPosition x_yPosition x_width x_height w_displayList t_pressCallback [x_backgroundColor]" "Creates a button to show a display list in.")
("dlMakePenTable" "[x_maxPens]" "Creates a pen table that a display list can use.")
("dlMakeStipple" "t_StippleString" "Creates a stipple pattern from a string.")
("dlMakeWidget" "[x_backgroundColor] [l_point1] [l_point2]" "Creates a general purpose window (or widget).")
("dlMapWidget" "x_widgetId" "Puts a widget back on the screen after a call to dlUnMapWidget( ). This function also applies to buttons.")
("dlMoveButton" "x_button x_xPosition x_yPosition" "Moves a button.")
("dlResizeButton" "x_button x_width x_height" "Resizes a button.")
("dlSaveDlist" "w_displayList t_fileName t_dlistName" "Saves the display list.")
("dlSetCurrentPen" "x_penNumber" "Sets the specified pen number to the current pen.")
("dlSetDlistPosition" "w_displayList x_widgetId x_xOffset x_yOffset" "Specifies the offsets to map from display list coordinates to screen coordinates.")
("dlSetDlistScale" "w_displayList x_widgetId f_scale" "Specifies the scale factor to map from display list coordinates to screen coordinates.")
("dlSetPenColor" "x_penNumber x_colorIndex [w_penTable]" "Changes a pen to the specified color index from the pen table.")
("dlSetPenFillStyle" "x_penNumber t_fillStyle [w_penTable]" "Sets the fill style of a pen.")
("dlSetPenStipple" "x_penNumber x_stippleId [w_penTable]" "Sets the stipple pattern for a pen.")
("dlSetPenTable" "w_displayList w_penTableOrDisplayList" "Sets the pen table for a display list.")
("dlSetWidgetName" "x_widgetId t_name" "Sets the text displayed in the window manager banner.")
("dlUnMapWidget" "x_widgetId" "Removes a widget from the screen, but does not destroy it. This function also applies to buttons.")
))
