(put 'dm_funs 'symbol-type "design management fun")
(setq dm_funs '(
("dmAddCellToCategory" "d_categoryId l_cellList" "Adds one or more cells to a cell category.")
("dmAddRefLib" "d_libraryId t_refLibraryName" "Adds a reference library to the beginning of a design library's reference library list.")
("dmAppendLib" "t_sourceLibraryName t_destLibraryName" "Appends the contents of the source library to the destination library.")
("dmAttachFile" "d_libraryId d_id t_fileName t_path t_attachType" "Attaches a file to an object.")
("dmChangeOwner" "d_libraryId t_oldOwnerName t_newOwnerName" "Changes the owner of every object in the library owned by t_oldOwnerName to t_newOwnerName.")
("dmCheck" "[d_libraryId]" "Checks the integrity of a library's metadata and file system.")
("dmCheckin" "d_libraryId t_cellName t_viewName t_inVersionNumber/nil t_path/nil s_advancePIndexFlag/nil t_logMessage/nil" "Checks in the new version of the checked-out and modified cellview data file.")
("dmCheckout" "d_libraryId t_cellName t_viewName t_versionNumber/nil t_intention/nil t_path_in/nil" "Checks out a version of the cellview file and stores it in the specified location.")
("dmClearCustomization" "l_cvSpecs" "Resets custom import or export information to nil.")
("dmCloseCellView" "d_libraryId d_versionId" "Closes the cellview version file.")
("dmCloseLib" "d_libraryId" "Decrements the open library counter and purges the library from memory when the count reaches 0.")
("dmCopyCell" "t_sourceLibName t_sourceCellName t_destLibName t_destCellName s_hierCopy s_sourceLibOnly" "Copies a cell identified by sourceLibName and sourceCellName to the destination cell identified by destLibName and destCellName.")
("dmCopyCellView" "t_sourceLibName t_sourceCellName t_viewName t_sourceVersionNumber t_destLibName/nil t_destCellName/nil" "Copies a cellview version from a source library to a destination library.")
("dmCreateCell" "d_libraryId t_cellName t_workingGroup/nil t_userGroup/nil" "Creates a cell.")
("dmCreateCellCategory" "d_LibraryOrCellCatId t_categoryName l_cellList" "Creates a cell category and places all specified cells within that category.")
("dmCreateCellView" "d_libraryId t_cellName t_viewName t_workingGroup/nil t_userGroup/nil" "Creates a cellview.")
("dmCreateLib" "t_libraryName [t_path/nil] [t_workingGroup/nil] [t_userGroup]" "Creates a library and opens it for editing.")
("dmCreateView" "d_libraryId t_viewName t_viewType/nil t_workingGroup/nil t_userGroup/nil" "Creates a view.")
("dmCustomizeImport" "cvSpecs ?file t_fileName [?cell t_cellName] [?view t_viewName] [?fileType g_dmFileType]" "Associates a cell name, view name, and/or file type with a file name that is under design manager control.")
("dmDeleteCell" "d_libraryId t_cellName" "Deletes a cell from a library.")
("dmDeleteCellView" "d_libraryId t_cellName t_viewName" "Deletes a cellview from a library.")
("dmDeleteLib" "t_libraryName [t_path]" "Deletes a library from disk.")
("dmDeleteRefLib" "d_libraryId t_refLibraryName" "Deletes a reference library from the reference library list of a design library. The reference library itself is not deleted.")
("dmDeleteVersion" "d_libraryId t_cellName t_viewName t_versionNumber" "Deletes a version of a cellview.")
("dmDeleteView" "d_libraryId t_viewName" "Deletes a view from the library.")
("dmDetachFile" "d_libraryId d_id t_fileName" "Disassociates an attached file from an object. Does not delete the file.")
("dmExport" "?library t_libraryName ?config t_configName [?dest t_location] [?foreign t/nil] [?overwrite t/nil] [?cleanup t/nil] [?customExport l_cvSpecs]" "Opens a configuration (if foreign is nil) or copies data from a library to a directory (if foreign is t).")
("dmExtract" "d_libraryId t_cellName t_viewName t_versionNumber t_path_in/nil" "Retrieves a data file for viewing or copying, without requiring a later checkin.")
("dmFindCell" "d_libraryId t_cellName" "Finds the identifier of a cell.")
("dmFindCellView" "d_libraryId t_cellName t_viewName" "Finds the identifier of a cellview.")
("dmFindLib" "t_libraryName" "Finds the identifier of the library, if the library is open.")
("dmFindVersion" "d_libraryId t_cellName t_viewName t_versionNumber" "Finds the identifier for a cellview version.")
("dmFindView" "d_libraryId t_viewName" "Finds the identifier of a view.")
("dmFix" "d_libraryId" "Fixes corruption of library metadata.")
("dmGenLibPathLibName" "" "Generates a list of the library name and directory path of each library that can be located using the library search path.")
("dmGenOpenCellView" "" "Generates a list of the open cellview versions in the open libraries.")
("dmGenOpenLibPathName" "" "Generates a list of the open library name and its directory path for each library that is open.")
("dmGetAttachedFile" "d_libraryId d_id t_fileName" "Gets the path of a file attached to an object.")
("dmGetCellViewPath" "d_libraryId t_cellName t_viewName t_versionNumber/nil" "Returns the file path of a version of a cellview, if it is open.")
("dmGetCheckLevel" "" "Returns the library check level used to trigger the start of dmLibCheck.")
("dmGetDefaultAccess" "" "Returns the owner, working group, user group, and public default access values for libraries, cells, views, and cellviews.")
("dmGetEditExportList" "" "Lists all the user login names and group names in the edit export list.")
("dmGetImportList" "" "Lists all the user login names and group names in the import list.")
("dmGetImportPath" "t_library t_config" "Returns the directory from which the non-Cadence data was imported.")
("dmGetLibPath" "" "Returns the library search path.")
("dmGetReadExportList" "" "Lists all user login names and group names in the read export list.")
("dmGetRefreshTimePeriod" "" "Gets the library refresh timeout value.")
("dmImport" "?library t_libraryName [?config t_configName] [?configType t_configType] [?cleanup t/nil] [?customImport l_cvSpecs] [l_subConfigSpecs]" "Brings non-Cadence data under the control of the design data management system.")
("dmInstallCellView" "d_libraryId t_cellName t_viewName t_path t_logMessage/nil" "Installs the data for the first version of a cellview.")
("dmLibCheck" "d_libraryId" "Checks the integrity of library metadata.")
("dmLockFile" "t_fileName" "Locks a file.")
("dmMakeViewClone" "t_libraryName/nil t_viewName d_viewId_in" "Creates a view object t_viewName in a library and then copies all the properties of the view d_viewId_in to it.")
("dmMapAttachFilePath" "t_libraryName t_libraryRootPath t_objectName n_objectIndex t_fileName n_objectType" "Maps the logical name of an attached file to a path indicating the physical location of the file.")
("dmMapFilePath" "t_libraryName t_libraryRootPath t_cellName n_cellIndex t_viewName n_viewIndex n_primaryIndex n_secondaryIndex n_deltaPrimaryIndex n_deltaSecondaryIndex t_userId n_mappingType" "Maps the logical name of a cellview version to a path indicating the physical location of a data file.")
("dmOpenCellView" "d_libraryId t_cellName t_viewName t_versionNumber/nil t_mode t_path/nil" "Opens a cellview for editing or reading.")
("dmOpenLib" "t_libraryName [t_path/nil [t_unused/nil [t_mode/nil] ] ]" "Opens a design library.")
("dmOpenRefLib" "t_refLibraryName d_designLibraryId" "Opens a reference library.")
("dmPurgeLib" "d_libraryId" "Closes the library for all applications and removes the library from virtual memory.")
("dmPurgeVersions" "d_libraryId t_cellNamePattern t_viewNamePattern t_versionNamePattern t_testExpression" "Deletes all matching versions of a cellview. If all versions match, deletes the cellview as well.")
("dmReOpenCellView" "d_versionId t_mode" "Changes the access mode of an open cellview.")
("dmRegMapAttachFile" "d_libraryId t_path" "Registers a file-mapping function for files attached to a library, cell, or view.")
("dmRegMapFile" "d_libraryId t_path" "Registers a file-mapping function for versions of cellview files.")
("dmRegTrigger" "s_functionName s_triggeringEvent" "Registers a function to be called when a triggering event occurs.")
("dmRemoveCellCategory" "d_categoryId" "Removes a cell category from a library or from a parent cell category.")
("dmRemoveCellFromCategory" "d_categoryId l_cellList" "Removes one or more cells from a cell category.")
("dmRenameLib" "t_origLibraryName t_newLibraryName" "Renames a library. The library remains in the same directory.")
("dmRenameRefLib" "t_designLibName t_origRefLibName t_newRefLibName" "Changes the reference library t_origRefLibName of library t_designLibName to t_newRefLibName. The instance masters placed inside cellviews of the library that refer to the original reference library are also changed to refer to the new reference library.")
("dmRestoreOwnerAccess" "t_libName [t_libPath]" "Restores the library owner's read, write, and delete privileges for a library. Only the library owner can execute this function.")
("dmRestoreVersionBackup" "d_libraryId t_cellName t_viewName t_versionNumber" "Replaces the file containing the checked-out version of a cellview with its backup file, if there is one.")
("dmSaveCellView" "d_versionId" "Informs data management that cellview data has been saved. Does not actually save the data.")
("dmSetCheckLevel" "x_level" "Specifies the checks to be run by dmLibCheck.")
("dmSetDefaultAccess" "l_defaultOwnerAccess l_defaultWorkingGroupAccess l_defaultUserGroupAccess l_defaultPublicAccess" "Sets the default access values for the owner, working group, user group, and public.")
("dmSetEditExportList" "t_export/nil" "Sets the user login names and group names in the edit export list.")
("dmSetImportList" "t_import/nil" "Sets the user login names and group names in the import list.")
("dmSetLibPath" "t_pathList" "Sets the library search path.")
("dmSetReadExportList" "t_export/nil" "Sets the user login names and group names in the read export list.")
("dmSetRefreshTimePeriod" "x_timeoutValue" "Sets the library read update timeout checking value.")
("dmUnRegMapAttachFile" "d_libraryId" "Cancels registration of a user-defined file-mapping function for files attached to a library, cell, or view object.")
("dmUnRegMapFile" "d_libraryId" "Cancels registration of a user-defined file-mapping function for versions of cellview files.")
("dmUncheckout" "d_libraryId t_cellName t_viewName t_versionNumber" "Cancels the checkout of the designated version.")
("dmUnlockFile" "x_lockId" "Releases a file lock set by dmLockFile.")
("dmUnregTrigger" "s_functionName s_triggeringEvent" "Unregisters a function, so it is no longer called when the triggering event occurs.")
("dmbLibBrowserFormDone" "s_formtype" "Defines whether the Library Browser window remains open, becomes an icon, or closes when you close a form.")
("dmbSetBrowserInteractions" " ?openDesignOption sl_openDesignOption ] [ ?openPlaceInstanceOption sl_openPlaceInstanceOption ] [ ?openOthersOption sl_openOthersOption ][ ?closeDesignOption t_closeDesignOption ][ ?closePlaceInstanceOption t_closePlaceInstanceOption ] [ ?closeOthersOption t_closeOthersOption ]" "Determines how the opening or closing of forms affects the Library Browser.")
("dmbSyncWithCellForm" "s_form s_synctype s_libraryName s_cellName [s_viewName] [s_versionNumber]" "Synchronizes a form with the Library Browser.")
("dmbSyncWithForm" "s_form s_synctype s_libraryName s_cellName s_viewName [s_versionNumber]" "Synchronizes a form with the Library Browser.")
("dmbUpdateBrowser" "" "Ensures that information typed in the library, cell, view, and version fields of a form causes a corresponding selection in the Library Browser, and ensures that selections made in the Library Browser are entered in the form.")
("dmAddAFEntryToConfig" "d_libraryId t_configName t_objectName t_filename t_attachType")
("dmAddCVEntryToConfig" "d_libraryId t_configName t_cellName t_viewName t_versionNumber t_bindingType")
("dmAddSubConfigToConfig" "d_libraryId t_configName t_libraryName t_subConfigName")
("dmAssignDefaultConfig" "d_libraryId t_configName")
("dmCloseConfig" "d_libraryId")
("dmCompileConfigTemplate" "t_filename")
("dmCreateConfigInstance" "d_libraryId t_configInstanceName t_postfix t_configTemplateName t_workingGroup t_userGroup")
("dmCreateConfigTemplate" "d_libraryId t_configName t_workingGroup t_userGroup")
("dmDeleteConfig" "d_libraryId t_configName")
("dmDumpConfig" "d_libraryId t_configName t_path n_hierarchy")
("dmFindConfig" "d_libraryId t_configName")
("dmInstallConfigTemplate" "d_libraryId l_parsingResult")
("dmOpenConfig" "d_libraryId t_configName")
("dmRefreshConfig" "d_libraryId")
("dmRemoveAFEntryFromConfig" "d_libraryId t_configName t_objectName t_filename n_attachType")
("dmRemoveCVEntryFromConfig" "d_libraryId t_configName t_cellName t_viewName")
("dmRemoveSubConfigFromConfig" "d_libraryId t_configName t_libraryName t_subConfigName")
("dmReplaceCVEntryInConfig" "d_libraryId t_configName t_cellName t_viewName t_versionNumber n_bindingType")
("dmResetDefaultConfig" "d_libraryId")
))
