(put 'gr_funs 'symbol-type "global routing fun")
(setq gr_funs '(
("grAutoBias" "d_cv d_net")
("grAvoidRouting" "d_channel g_avoidStatus")
("grClose" "d_cv")
("grExpand" "d_cv d_net t_congestionCost t_expansionMode")
("grInit" "d_cv t_statFile t_tempPinFile [g_stubRoute]")
("grPrintNetPairs" "d_cv")
("grRegisterNetPair" "d_cv d_net1 d_net2 g_register")
("grRouteAll" "d_cv {(d_CV)|l_net} t_expansionMode t_congestionCost")
("grTree" "d_cv d_net l_(t_horizBias t_vertBias) t_congestionCost t_expansionMode")
("grUndoAll" "d_cv")
("grUndoNet" "d_cv d_net")
))
