(put 'le_funs 'symbol-type "layout editor fun")
(setq le_funs '(
("leAttachFig" "d_figId1 d_figId2")
("leChopShape" "d_shapeId l_points g_closed [g_remove] [x_sides]")
("leClearAllRuler" "d_cellViewId")
("leConvertShapeToPolygon" "d_shapeId [x_sides]")
("leCreateAutoInstPin" "d_cellViewId l_point t_termName t_termDir")
("leCreateAutoPin" "d_cellViewId l_point t_termName t_termDir")
("leCreateContact" "d_cellViewId t_contact l_origin t_orient n_width n_length x_rows x_cols n_xPitch n_yPitch t_xBias t_yBias")
("leCreatePath" "d_cellViewId l_layerPurposePair l_points n_width [t_pathStyle] [n_offset] [t_justification]")
("leCreatePin" "d_cellViewId l_layerPurposePair t_shape l_points t_termName t_termDir l_accessDir")
("leCreateRuler" "d_cellViewId l_points")
("leDeiconifyLSW" "")
("leDescend" "w_windowId d_instId [x_row] [x_column]")
("leEditDesignProperties" "[d_cellviewId]")
("leEditInPlace" "w_windowId l_hierlist")
("leFlattenInst" "d_instId x_levels [g_flattenPCells] [g_preservePins]")
("leGetContactDefaultParam" "d_cellViewId")
("leGetContactNameArray" "d_libId")
("leGetContactParam" "d_instId")
("leGetContactRule" "d_cellViewId")
("leGetEntryLayer" "[d_libId]")
("leGetEnv" "t_name")
("leGetRefPoint" "d_cellViewId")
("leGetValidLayerList" "d_libId")
("leHiAttach" "[w_windowId]")
("leHiChop" "[w_windowId]")
("leHiClearRuler" "[w_windowId]")
("leHiConvertShapeToPolygon" "[w_windowId]")
("leHiCopy" "[w_windowId]")
("leHiCreateBend" "[w_windowId]")
("leHiCreateCircle" "[w_windowId]")
("leHiCreateContact" "[w_windowId]")
("leHiCreateDonut" "[w_windowId]")
("leHiCreateEllipse" "[w_windowId]")
("leHiCreateInst" "[w_windowId]")
("leHiCreateLabel" "[w_windowId]")
("leHiCreatePath" "[w_windowId]")
("leHiCreatePin" "[w_windowId]")
("leHiCreatePolygon" "[w_windowId]")
("leHiCreateRect" "[w_windowId]")
("leHiCreateRuler" "[w_windowId]")
("leHiCreateTaper" "[w_windowId]")
("leHiCreateTrl" "[w_windowId]")
("leHiDelete" "[w_windowId]")
("leHiDeleteAllAreaViewLevel" "[w_windowId]")
("leHiDeleteAreaViewLevel" "[w_windowId]")
("leHiDescend" "[w_windowId]")
("leHiEditDisplayOptions" "[w_windowId]")
("leHiEditEditorOptions" "")
("leHiEditInPlace" "[w_windowId]")
("leHiEditProp" "[w_windowId]")
("leHiFlatten" "[w_windowId]")
("leHiLayerGen" "[w_windowId]")
("leHiLayerTap" "[w_windowId]")
("leHiMakeCell" "[w_windowId]")
("leHiMerge" "[w_windowId]")
("leHiModifyCorner" "[w_windowId]")
("leHiMove" "[w_windowId]")
("leHiMoveOrigin" "[w_windowId]")
("leHiPaste" "[w_windowId]")
("leHiReshape" "[w_windowId]")
("leHiSearch" "[w_windowId]")
("leHiSetAreaViewLevel" "[w_windowId]")
("leHiSetRefPoint" "[w_windowId]")
("leHiSetValidLayer" "")
("leHiShowSelSet" "[w_windowId]")
("leHiSize" "[w_windowId]")
("leHiSplit" "[w_windowId]")
("leHiStretch" "[w_windowId]")
("leHiSummary" "[w_windowId]")
("leHiTree" "[w_windowId]")
("leHiYank" "[w_windowId]")
("leIconifyLSW" "")
("leIsContact" "d_instId")
("leIsContactMaster" "d_cellViewId")
("leIsContactName" "d_libId t_contactName")
("leIsFigSelectable" "d_figId")
("leIsInstSelectable" "[d_libId]")
("leIsLSWIconified" "")
("leIsLayerSelectable" "l_layerPurposePair [d_libId]")
("leIsLayerValid" "l_layerPurposePair [d_libId]")
("leIsLayerVisible" "l_layerPurposePair [d_libId]")
("leIsPinSelectable" "[d_libId]")
("leIsRefPointActive" "d_cellViewId")
("leLayerAnd" "d_cellViewId g_lpp1 g_lpp2 g_lpp3")
("leLayerAndNot" "d_cellViewId g_lpp1 g_lpp2 g_lpp3")
("leLayerOr" "d_cellViewId g_lpp1 g_lpp2 g_lpp3")
("leLayerSize" "d_cellViewId g_lpp1 n_sizeAmount g_lpp2")
("leLayerXor" "d_cellViewId g_lpp1 g_lpp2 g_lpp3")
("leMakeCell" "l_figs t_libName t_cellName t_viewName g_replace")
("leMergeShapes" "l_shapes [x_sides]")
("leModifyCorner" "d_figId l_selArray g_chamfer x_distance [x_sides]")
("leMoveCellViewOrigin" "d_cellViewId l_point")
("leMoveCursor" "f_dX f_dY")
("leMoveCursorToRefPoint" "")
("lePasteFigs" "d_cellViewId l_destPt [t_rotation]")
("leReplace" "d_cellViewId l_objects l_replaceValues")
("leResizeLSW" "l_bBox")
("leSearchHierarchy" "d_cellViewId l_bBox x_stopLevel t_objectType l_criteriaList")
("leSetAllLayerSelectable" "g_isSelectable [d_libId]")
("leSetAllLayerValid" "g_isValid [d_libId]")
("leSetAllLayerVisible" "g_isVisible [d_libId]")
("leSetContactParam" "d_instId n_width n_length x_rows x_columns n_xPitch n_yPitch t_xBias t_yBias")
("leSetEntryLayer" "l_layerPurposePair [d_libId]")
("leSetEnv" "t_name g_value")
("leSetInstSelectable" "g_isSelectable [d_libId]")
("leSetLayerSelectable" "l_layerPurposePair g_isSelectable [d_libId]")
("leSetLayerValid" "l_layerPurposePair g_isValid [d_libId]")
("leSetLayerVisible" "l_layerPurposePair g_isVisible [d_libId]")
("leSetPinSelectable" "g_isSelectable [d_libId]")
("leSetRefPoint" "d_cellViewId l_point")
("leSetRefPointInactive" "d_cellViewId")
("leSizeShape" "d_shapeId g_sizeFactor")
("leSplitShape" "d_shapeId l_delta l_splitLine g_leftOrRight [g_lockAngles]")
("leStretchShape" "d_shapeId l_delta l_freePoints [g_lockAngles]")
("leToggleGravity" "")
("leYankFigs" "d_cellViewId l_ptArray x_nLevels [l_refPt] [x_nSides]")
))
