(put 'mi_funs 'symbol-type "framemaker interchange fun")
(setq mi_funs '(
("mifAFrames" "[l_frameSubstatement1 ... l_frameSubstatementN]" "Generates the SMIFT representation of the MIF AFrames statement.")
("mifAppend1" "l_compoundStmt l_substmt" "Creates a new compound statement by concatenating a new single statement onto the end of a group of statements embedded within the compound statement.")
("mifAppendN" "l_compoundStmt l_groupOfSubstmts" "Creates a new compound statement by concatenating a group of statements onto the end of another group of statements embedded within a compound statement.")
("mifArc" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Arc statement.")
("mifArrowStyle" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF ArrowStyle statement.")
("mifChar" "s_characterName" "Generates the SMIFT representation of the MIF Char statement.")
("mifComment" "g_comment1 g_comment2 ... g_commentN" "Generates the SMIFT representation of the MIF Comment statement.")
("mifConc1" "l_compoundStmt l_substmt" "Concatenates a single statement onto the end of a group of statements embedded within a compound statement.")
("mifConcN" "l_compoundStmt l_groupOfSubstmts" "Concatenates a group of statements onto the end of another group of statements embedded within a compound statement.")
("mifDocument" "[l_documentSubstatement1 ... l_documentSubstatementN]" "Generates the SMIFT representation of the MIF Document statement.")
("mifEllipse" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Ellipse statement.")
("mifFont" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Font statement.")
("mifFontCatalog" "[l_fntCatalogSubstmt1 ... l_fntCatalogSubstmtN]" "Generates the SMIFT representation of the MIF FontCatalog statement.")
("mifFrame" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Frame statement.")
("mifGroup" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Group statement.")
("mifImportObject" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF ImportObject statement.")
("mifKeyFont" "[?key argument]" "Generates the SMIFT representation of the MIF Font statement. Equivalent to mifFont.")
("mifKeyPage" "[ ?key argument]" "Generates the SMIFT representation of the MIF Page statement. Equivalent to mifPage.")
("mifKeyPgf" "[ ?key argument ]" "Generates the SMIFT representation of the MIF Pgf statement. Equivalent to mifPgf.")
("mifMarker" "mifMType( x_markerTypeID" "Generates the SMIFT representation of the MIF Marker statement.")
("mifNotes" "[l_FNoteStatement1 ... l_FNoteStatementN]" "Generates the SMIFT representation of the MIF Notes statement.")
("mifPage" "[l_pageSubstatement1 ... l_pageSubstatementN]" "Generates the SMIFT representation of the MIF Page statement.")
("mifPara" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Para statement.")
("mifParaLine" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF ParaLine statement.")
("mifPgf" "[l_pgfSubstatement1 ... l_pgfSubstatementN]" "Generates the SMIFT representation of the MIF Pgf statement.")
("mifPgfCatalog" "[l_pgfCatalogSubstmt1 ... l_pgfCatalogSubstmtN]" "Generates the SMIFT representation of the MIF PgfCatalog statement.")
("mifPgfFont" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF PgfFont statement.")
("mifPolyLine" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF PolyLine statement.")
("mifPolygon" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Polygon statement.")
("mifPush1" "l_substmt l_compoundStmt" "Concatenates a single substatement to the head of a group of substatements embedded within a compound statement.")
("mifPushN" "l_groupOfSubstmts l_compoundStmt" "Concatenates a group of substatements to the head of another group of substatements embedded within a compound statement.")
("mifRectangle" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF Rectangle statement.")
("mifRoundRect" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF RoundRect statement.")
("mifTextFlow" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF TextFlow statement.")
("mifTextLine" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF TextLine statement.")
("mifTextRect" "[l_substatement1 ... l_substatementN]" "Generates the SMIFT representation of the MIF TextRect statement.")
("mifUnits" "s_defaultUnits" "Generates the SMIFT representation of the MIF Units statement.")
("mifVariableFormats" "[l_formatSubstatement1 ... l_formatSubstatementN]" "Generates the SMIFT representation of the MIF VariableFormats statement.")
("mifVerbose" "s_ Yes | No" "Generates the SMIFT representation of the MIF Verbose statement.")
("mifXRefFormats" "[l_formatSubstatement1 ... l_formatSubstatementN]" "Generates the SMIFT representation of the MIF XRefFormats statement.")
))
