(put 'mm_funs 'symbol-type "module maker fun")
(setq mm_funs '(
("mmAbortGenerator" "")
("mmAddLineToTable" "l_tconcTable @rest t_args")
("mmAlignPoint" "l_locInCell l_target [t_orient]") 
("mmBuildDelayTable" "l_delayPlistList")
("mmCalcDelays" "l_params l_delayPlistList l_capacitancePlist")
("mmCalcPlistDelays" "l_params l_delayPlist n_capacitance")
("mmCheckDelayPlist" "l_delayPlist")
("mmCheckDelayPlistList" "l_delayPlistList")
("mmClearPDFCellView" "")
("mmCreateModule" "t_fileName [lt_lib&cellName] [g_promptP] [l_paramList]") 
("mmDefCellName" "t_cellName")
("mmDefParameters" "(name t_parameterName type t_valueType default g_defaultValue [prompt t_prompt] [constraints l_constraintExpr] [compare t/nil] [affectedStages l_stageNames])...")
("mmDefTerminals" "(type t_terminalType name tl_terminalName [width x_terminalWidth] [property (S_propertyName = g_propertyValue ...)])")
("mmDefVariables" "(type t_valueType name t_variableName [default g_defaultValue]) [compare t/nil]...")
("mmDefineDelayTable" "[lt_lib&cellName (l_delayTable)]")
("mmDefinePCell" "t_cellname (('s_formalParam g_defValue) ('s_formalParam g_defValue) ...) l_contents")
("mmDefinePinToPinDelay" "[lt_lib&cellName] (tl_inputTerm tl_outputTerm fl_delay [t_transform])")
("mmDotPin" "(t_layer [t_purpose]) l_coords l_dimensions t_termIO t_netName [t_pinName [lt_accessDirs]]")
("mmDrawWFNote" "d_cellViewId x_noteIndex t_note [l_optionPairs]")
("mmDrawWFSectionLine" "d_cellViewId f_xLocation x_fromTrace x_toTrace t_sectionLabel t_orient [l_optionPairs]")
("mmDrawWFTitle" "d_cellViewId t_title [l_optionPairs]")
("mmDrawWFTrace" "d_cellViewId x_traceIndex l_points [g_busP]")
("mmDrawWFTraceLabel" "d_cellViewId x_traceIndex t_ltLowLabel t_ltHighLabel [t_rtLowLabel] [t_rtHighLabel] [l_optionPairs]")
("mmDrawWFXaxis" "d_cellViewId f_start f_end f_increment [g_displayP] [l_optionPairs]")
("mmDrawWFYaxis" "d_cellViewId f_start f_end f_increment [g_display]")
("mmEncrypt" "t_infile t_outfile") 
("mmExecuteStage" "lt_lib&cellName Sl_stages") 
("mmExtractSpiceDelays" "l_delayPlistList  t_simulationDir")
("mmExtractWsfSpiceDelay" "p_wsfPort l_delayPlist [l_netXrefPlist]")
("mmForgetStageCellView" "")
("mmGenSimCellView" "[lt_lib&cellName] t_targetViewName [t_propName = g_propValue] ... [t_propName = g_propValue]")
("mmGenTaModel" "[delayTable( l_delayTable)] [t_propName = g_propValue] ... [t_propName = g_propValue]") 
("mmGenVerilogCellView" "[lt_lib&cellName] S_modelName S_modelFileName g_terminalList g_isPrimGateP [t_propName = g_propValue] ... [t_propName = g_propValue]") 
("mmGetAffectedStages" "st_parameterName")
("mmGetCellView" "lt_lib&CellName t_viewName [t_mode]") 
("mmGetCurrentCellName" "")
("mmGetCurrentStageName" "")
("mmGetDefinedStages" "lt_lib&cellName") 
("mmGetDelayTable" "[lt_lib&cellName]")
("mmGetExecutedStages" "[lt_lib&cellName]")
("mmGetNetCapacitancePlist" "tl_libCellSpec l_delayPlistList [ n_minValue [ n_unitAdjust ]]")
("mmGetPDFCellView" "")
("mmGetParameters " "[lt_lib&cellName]") 
("mmGetPinToPinDelay" "[lt_lib&cellName] tl_inputTerm tl_outputTerm")
("mmGetPredStages" "[st_stage]")
("mmGetStageCellView" "")
("mmGetTerminals" "[lt_lib&cellName]") 
("mmGetVariables" "[lt_lib&cellName]") 
("mmHIGetMenu" "")
("mmInputPinFormat" "t_simulatorName [t_inputPinString]") 
("mmInstPinBBox" "d_instance t_termName [t_pinName]") 
("mmInstPinLayer" "d_instance t_termName [t_pinName]") 
("mmInstPinLoc" "d_instance t_termName [t_pinName]") 
("mmIsAffectedStage" "st_parameterName st_checkingStage")
("mmIsPredStage" "[st_targetStage] st_checkingStage")
("mmIsStageExecuted" "lt_lib&cellName S_stageName") 
("mmMakeModules" "d_cellView Sl_stages [g_traverseHierP] [t_viewSwitchList]") 
("mmModifyModule" "lt_lib&cellName Sl_stagelist [g_overwriteP] [g_promptP] [l_parameterList]")
("mmPin" "(t_layer [t_purpose]) l_coords t_termIO t_netName [t_pinName [lt_accessDirs]]") 
("mmPinBBox" "t_termName [t_pinName [d_cellView]]")
("mmPinLoc" "t_termName [t_pinName [d_cellView]]")
("mmPlaceCell" "d_masterCellViewId l_origin [t_instName [t_orient [x_numInst]]]") 
("mmPlaceDocTable" "lt_lib&cellName t_viewName t_justification l_heading l_text [l_text] ...") 
("mmPlacePCell" "d_supermasterCellViewId l_origin (l_name_value_lists) ...")
("mmQueryModule" "lt_lib&cellName") 
("mmReplaceTokens" "t_inputFileName t_outputFileName g_replacementList") 
("mmRouteAllNets" "d_cellView t_preferredLayer t_preferredLayerDir t_secondLayer [l_powerNetInfos]   [g_minimizeVias]") 
("mmSchWire" "[t_wireName] [x_pathWidth] l_origin l_directives")
("mmSetPDFCellView" "d_cellView")
("mmSetPredStages" "st_stage tl_predecessorStages g_executeP")
("mmSetStageCellView" "d_cellviewId")
("mmSetVariable" "t_variableName g_variableValue [lt_lib&cellName]")
("mmStdGBuildAbstract" "t_cellName l_parameters")
("mmStdGBuildDoc" "t_simName l_parameters  d_extractedCellviewId d_symbolCellviewId l_inTermNames") 
("mmStdGBuildExtracted" "t_cellName l_parameters g_parasiticsp") 
("mmStdGBuildFramed" "t_cellName l_parameters") 
("mmStdGBuildLayout" "t_cellName l_parameters") 
("mmStdGBuildSilos" "t_simName l_parameters  d_cellviewId l_inTermNames") 
("mmStdGBuildStl" "l_parameters  t_cellName  t_simDir t_simName")
("mmStdGCheckPrev" "l_parameters") 
("mmStdGDefineResultList" "l_parameters t_stageName t_simDir") 
("mmStdGDefineTech" "d_libraryId") 
("mmStdGDffTruthTab" "l_parameters") 
("mmStdGDffVecList" "l_parameters  t_cellName f_inputTransVolt f_outputTransVolt") 
("mmStdGDocDelays" "l_parameters l_delayPair x_outNetCapacitance") 
("mmStdGExtractWsfSpiceDelay" "t_wsfTextFileName t_wsfInputName f_inpInitialTime g_inputEdgeRisingp f_inputTransVolt t_wsfOutputName g_outputEdgeRisingp f_outputTransVolt f_logicHiVoltage f_logicLoVoltage") 
("mmStdGFilterResultList" "l_inputNetNames l_outputNetNames l_delayTypes l_resultList s_operator") 
("mmStdGFindDffNets" "t_cellName  g_scanp") 
("mmStdGModifyResultStr" "l_resultList") 
("mmStdGPrintSilosMacros" "t_fullPathName") 
("mmStdGRedefine" "d_libraryId t_layerString x_pnRatio") 
("mmStdGTotalNetCapacitance" "d_cellviewId t_netName") 
("mmStdGXrefSpiceNets" "t_simDir l_extractedNetNames") 
("mmSymbolLoc" "d_instance") 
("mmTotalNetCapacitance" "d_cvid t_netName")
("mmWire" "l_directives") 
("mmWriteEPSDelayTable" "t_epsFileName l_delayPlistList")
("mmWriteEPSinputCapacitanceTable" "t_epsFileName l_delayPlistList l_capacitancePlist")
("mmXrefSpiceNets" "t_simulationDir l_nameList")
))
