(put 'pc_funs 'symbol-type "parameterized cell fun")
(setq pc_funs '(
("pcCompileToSkill" "d_cvId")
("pcDefineCondition" "d_cvId l_figs l_namelist g_condition g_stretch f_adjust")
("pcDefineInheritParam" "d_instId s_parameter g_value l_namelist")
("pcDefinePCell" "l_cellIdentifier l_formalArgs code")
("pcDefineParamLabel" "d_labelId S_height")
("pcDefineParamLayer" "d_cvId l_shapes g_layerExpr l_namelist [g_purposeExpr]")
("pcDefineParamPath" "d_pathId S_param g_margin g_width n_defaultWidth t_snap l_namelist")
("pcDefineParamPolygon" "d_polygonId S_param g_margin t_snap l_namelist")
("pcDefineParamProp" "d_cvId t_name g_expr")
("pcDefineParamRect" "d_rectangleId S_param g_margin l_namelist")
("pcDefineParamRefPointObject" "g_objects S_param l_refpoint")
("pcDefinePathRefPointObject" "g_objects S_param t_endpoint")
("pcDefineRepeat" "d_cvId l_shapes l_namelist g_stepX g_stepY g_repeatX g_repeatY g_stretchX g_stretchY g_adjustX g_adjustY t_direction")
("pcDefineSteppedObject" "g_objects S_param g_step g_startOffset g_endOffset l_namelist")
("pcDefineStretchLine" "d_lineId g_paramExpr t_direction f_defval f_minval f_maxval g_stretchRepeated")
("pcDeleteCondition" "d_groupId")
("pcDeleteParam" "d_cvId S_param")
("pcDeleteParamLayer" "d_groupId")
("pcDeleteParamProp" "d_cvId t_propname")
("pcDeleteParamShape" "d_memberId")
("pcDeleteRefPoint" "d_groupId")
("pcDeleteRepeat" "d_groupId")
("pcDeleteSteppedObject" "d_groupId")
("pcGetConditions" "d_cvId")
("pcGetInheritParamDefn" "d_instId")
("pcGetInheritParams" "d_cvId")
("pcGetParamLabelDefn" "d_labelId")
("pcGetParamLabels" "d_cvId")
("pcGetParamLayerDefn" "d_instId")
("pcGetParamLayers" "d_cvId")
("pcGetParamProps" "d_cvId")
("pcGetParamShapeDefn" "d_instId")
("pcGetParamShapes" "d_cvId")
("pcGetParameters" "d_cvId")
("pcGetRefPointDefn" "d_objectId")
("pcGetRefPoints" "d_cvId")
("pcGetRepeatDefn" "d_objectId")
("pcGetRepeats" "d_cvId")
("pcGetSteppedObjectDefn" "d_objectId")
("pcGetSteppedObjects" "d_cvId")
("pcGetStretchDefn" "d_objectId")
("pcGetStretches" "d_cvId")
("pcModifyParam" "d_cvId S_param t_type g_value")
("pcRedefineStretchLine" "d_lineId g_ paramExpr t_direction f_defval f_minval f_maxval g_stretchRepeated")
("pcRestrictStretchToObjects" "d_stretchId l_objlist")
))
