(put 'pl_funs 'symbol-type "plot fun")
(setq pl_funs '(
("plotGenEPS" "t_libName t_cellName t_viewName t_outputFile")
("plotSetAt" "t_atTime")
("plotSetCell" "t_name")
("plotSetHeaderInfo" "l_headerConts")
("plotSetLibrary" "t_name")
("plotSetMagnification" "g_mag")
("plotSetOutputFile" "t_name")
("plotSetPageSize" "t_pageSize")
("plotSetPageSizeWH" "l_plotSize")
("plotSetPlotter" "t_plotterName")
("plotSetSizeUnits" "t_unitName")
("plotSetStopList " "l_stopList")
("plotSetSwitchList" "l_switchList ")
("plotSetTitle1" "t_title")
("plotSetTitle2" "t_title")
("plotSetTitle3" "t_title")
("plotSetTmpDir" "t_directory")
("plotSetVersion" "t_name")
("plotSetView" "t_name")
("plotSetWindowBBox" "l_boundingBox")
("plotSetWindowSource" "t_windowSource")
))
