(put 'pr_funs 'symbol-type "global&detail routing fun")
(setq pr_funs '(
("prConnDowndate" "d_cv")
("prConnUpdate" "d_cv t_stubRoute")
("prConnUpdateNet" "d_net [t_stubRoute]")
("prCreateChannels" "d_cv t_mainDir t_prefix")
("prCreateCutlines" "d_cv t_mainDir")
("prDeleteChannels" "d_cv")
("prDeleteCutlines" "d_cv")
("prGrp" "d_cv l_parameters")
("prIglrConnUpdateNet" "d_net")
("prIglrConnectExit" "d_net t_subnetName t_exitSubnetName d_chan t_chanSide d_exitChan")
("prIglrConnectPin" "d_net t_subnetName d_devInst d_fPin d_chan t_accessDir")
("prIglrConnectSet" "l_pinSet l_exitSet d_net")
("prIglrDisconnectExit" "d_instId d_exitInst d_chan d_exitChan")
("prIglrDisconnectPin" "d_instId d_chan")
("prIglrFeedAssign" "d_Inst d_fPin d_net")
("prIglrFindExitInChannel" "exitList d_chan d_cvNet")
("prIglrFindInstInChannel" "area_bBox layerPurposePair d_chan d_net")
("prIglrFindPinInChannel" "pinList d_cvNet")
("prIglrGetAtermFromInstInst" "l_instInstList")
("prIglrGetChannelAccessPins" "d_chan d_net")
("prIglrGetNetByName" "d_cv t_netName")
("prIglrGetNewSubnetName" "d_net d_chan")
("prIglrGetOuterChannels" "d_cv t_returnType")
("prIglrGetPinAccessChannels" "d_cellInst d_fPin")
("prIglrGetPinAccessDir" "d_cellInst d_fPin")
("prIglrMergeSubnets" "d_net d_subnetA d_subnetB d_chan")
("prIglrVerifyRep" "d_cv")
("prIsAreaEstimated" "d_cv [v_verbose]")
("prRelAdjacency" "d_relId/d_instId t_direction [t_type]")
("prRelFindRel" "d_instId")
("prRelGetFirst" "d_relId")
("prRelGetInst" "d_relId")
("prRelGetLast" "d_relId")
("prRelGetNext" "d_relId")
("prRelGetParent" "d_instId")
("prRelGetPrevious" "d_relId")
("prRelGroupOf" "d_relId/d_instId [t_type]")
("prRelIsLeaf" "d_relId")
("prRelIsRel" "d_relId")
("prRelLeafGen" "d_relId/d_instId t_cellType [t_type]")
("prRelTopRel" "d_cv")
("prSave" "d_cv [t_viewName]")
("prSplitNet" "d_cv d_net")
("prUpdateNetStatus" "l_netId t_attribute t_newValue")
("praBlockPlace" "d_cv g_honorInit x_runMode f_wireLengthWeight f_RoutingArea x_softBlockLevel [f_aspLow] [f_aspHigh] [f_maxXdim] [f_maxYdim]")
("praGEBlockPlace" "d_cv g_honorInit x_runMode f_wireLengthWeight f_RoutingArea x_softBlockLevel")
("praOptimizeIO" "d_cv t_mode f_space f_var")
("prnDetailRouteCompacted" "d_cv lt_options")
("prnDetailUnroute" "d_cv")
("prnExplodeChannels" "d_cv")
("prnSetCRT" "x_layers x_multiBoundary")
("prnStripChan" "t_boundaryShape "rect" | "poly" n_boundaryExtension")
("prnUnrouteChannel" "d_chanInst")
))
