(put 'sc_funs 'symbol-type "sch HI|struct compiler fun")
(setq sc_funs '(
("scAddCell" "x_column:x_row t_icon t_direction [t_orientation]")
("scAddColumn" "x_column t_direction n_width")
("scAddMaster" "t_master-name t_icon")
("scAddRow" "x_row")
("scBias" "")
("scCellHeight" "t_icon")
("scCellHeight" "x_column:x_row")
("scCellWidth" "t_icon")
("scCellWidth" "x_column:x_row")
("scChangeBias" "t_bias")
("scChangeCell" "x_column:x_row t_icon [t_orientation]")
("scChangeIcon" "t_fromIcon t_toIcon")
("scChangeMaster" "t_icon t_master-name")
("scChangeOrient" "x_column:x_row t_orientation")
("scCompileArray" "d_layoutCellView d_templateCellView [t_personalityFile] [t_parameterValue] [t_procedureFile]")
("scDeleteCell" "x_column:x_row")
("scDeleteColumn" "x_column")
("scDeletePlane" "d_cellView t_planeName")
("scDeleteRow" "x_row")
("scDrawPlane" "d_cellView t_planeName l_bbox")
("scGetPlanePoint" "d_cellView [t_prompt]")
("scIcon" "x_column:x_row")
("scIcon" "t_master-name")
("scMaster" "t_icon|x_column:x_row")
("scOrient" "x_column:x_row")
("scPlane" "d_cellView t_plane-name ['g_SKILL-func 'g_SKILL-func...]")
("scPromotePin" "x_column:x_row t_terminal_name d_pinID")
("scResizePlane" "d_cellView t_planeName l_bbox")
("scStretchEmptyCell" "x_column:x_row [n_dimension]")
("scSwapCells" "x_column:x_row x_column:x_row [t_orientation [t_orientation]]")
("scSwapColumns" "x_column x_column")
("scSwapRows" "x_row x_row")
("scUnusedIcon" "")
("schAddSelectPt" "")
("schDirectEdit" "x_index")
("schExtendSelectPt" "")
("schGetEnv" "[t_variableName]")
("schHiAlternateView" "")
("schHiCellViewProperty" "")
("schHiChangeEditMode" "t_newMode")
("schHiCheck" "[t_action]")
("schHiCheckAndSave" "")
("schHiCheckHier" "[t_action] [t_refLibs]")
("schHiCloneSymbol" "[t_libraryName] [t_cellName] [t_viewName]")
("schHiComputePinRef" "[s_reportFile] [t_display] [s_formatString] [t_reportDups] [t_sortByDir]")
("schHiCopy" "[s_formFlag] [x_numrows] [x_numcols] [t_useSelSet]")
("schHiCreateBlockInst" "[t_libraryName] [t_cellName] [t_viewName] [t_blockSampleName] [t_instanceName] [t_pinNameSeed]")
("schHiCreateInst" "[t_libraryName] [t_cellName] [t_viewName] [t_instanceName] [x_rows] [x_columns]")
("schHiCreateInstBox" "[s_autoBox]")
("schHiCreateNoteLabel" "[t_text] [t_justify] [t_fontStyle] [n_fontHeight] [t_type]")
("schHiCreateNoteShape" "[t_shape] [t_style] [x_width]")
("schHiCreatePin" "[t_terminalName] [t_direction] [t_usage] [t_interpret] [t_mode]")
("schHiCreateSheet" "[n_number] [t_size] [t_type]")
("schHiCreateSimBox" "[t_signalName] [t_type]")
("schHiCreateSymbolLabel" "[t_labelChoice] [t_text] [t_justify] [t_fontStyle] [n_fontHeight] [t_type]")
("schHiCreateSymbolPin" "[t_terminalName] [t_type] [t_direction] [t_interpret] [t_mode] [n_incrCount] [t_location]")
("schHiCreateSymbolShape" "[t_shape] [t_style] [x_width]")
("schHiCreateWire" "[n_width] [t_drawMode] [t_routeMethod] [t_lockAngle]")
("schHiCreateWireLabel" "[t_text] [t_purpose] [t_justify] [t_fontStyle] [n_fontHeight] [t_interpret] [t_mode]")
("schHiDelete" "")
("schHiDeleteIndex" "")
("schHiDeleteSheet" "[n_startSheet] [n_endSheet]")
("schHiDescendEdit" "@optional [w_window]")
("schHiDescendRead" "@optional [w_window]")
("schHiDisplayOptions" "@optional [w_window]")
("schHiDrawSymbolPin" "[t_terminalName] [t_direction] [t_interpret]")
("schHiEditInPlace" "@optional [w_window]")
("schHiEditPinOrder" "[s_updateInstLastChanged]")
("schHiEditSheetSize" "[t_size] [t_type]")
("schHiEditTitleBlock" "")
("schHiEditorOptions" "@optional [w_window]")
("schHiExtractConn" "[t_action]")
("schHiFind" "[t_propName] [t_condOp] [t_propValue]")
("schHiFollowPin" "[t_order]")
("schHiGotoSheet" "[g_sheetNum]")
("schHiGridOptions" "[w_window]")
("schHiHiliteLabel" "[t_labelType] [t_display]")
("schHiInstToView" "[t_viewName]")
("schHiMousePopUp" "")
("schHiMove" "[t_useSelSet]")
("schHiObjectProperty" "")
("schHiOpenCellView" "")
("schHiPinListToView" "[t_libName] [t_cellName] [t_viewName] [l_inPinList] [l_outPinList] [l_ioPinList] [l_swPinList]")
("schHiPlot" "")
("schHiPlotQueueStatus" "")
("schHiRenumberAllSheet" "")
("schHiRenumberSheet" "[n_from] [n_to]")
("schHiReplace" "[x_replaceAll] [t_propName] [t_condOp] [t_propValue] [t_newPropName] [t_newPropValue]")
("schHiReturn" "@optional [w_window]")
("schHiReturnToTop" "@optional [w_window]")
("schHiRotate" "[g_nonModal]")
("schHiRouteFlightLine" "[t_routeMethod]")
("schHiSRC" "[t_action]")
("schHiSaveCellView" "")
("schHiSelectAll" "")
("schHiSelectByProperty" "[t_selectp] [t_propName] [t_condOp] [t_propValue]")
("schHiSetSymbolOrigin" "")
("schHiShowAllMarker" "[t_source] [t_severity]")
("schHiShowScope" "@optional [w_window]")
("schHiSolder" "")
("schHiStretch" "[t_routeMethod] [t_useSelSet]")
("schHiSymStretch" "t_useSelSet")
("schHiUpdatePinOrder" "[s_updateInstLastChanged]")
("schHiVHDLProperty" "")
("schHiVIC" "[t_viewList]")
("schHiViewToView" "[t_libName] [t_cellName] [t_viewNameFrom] [t_viewNameTo]")
("schSetEnv" "[t_variableName] [g_value]")
("schSetSelectOptions" "")
("schSingleSelectPt" "")
))
