(put 'sy_funs 'symbol-type "compactor fun")
(setq sy_funs '(
("syActivateConstraint" "d_constObjId")
("syCompactView" "d_inputCVId l_outputCVName g_hierP")
("syCreateAlignmentConstraint" "t_direction l_objectLists [?unrelaxable]")
("syCreateFence" "d_inputCVId l_layerPurposePair l_points g_rectOrNot")
("syCreateJogConstraint" "d_dbWireId l_point")
("syCreateMagneticConstraint" "t_direction l_object1 l_object2 t_magneticType")
("syCreateSeparationConstraint" "t_direction l_object1 l_object2 l_minMaxSeparation [?unrelaxable] [?ignoreDRC]")
("syCreateWireWidthConstraint" "d_dbWireId n_finalWidth")
("syDRC" "d_inputCVId d_runDir")
("syDeactivateConstraint" "d_constObjId")
("syDeleteConstraint" "d_constObjId")
("syERC" "d_inputCVId d_runDir")
("syExtractView" "d_inputCVId l_outputCVName g_hierP")
("syFrameView" "d_inputCVId l_outputCVName n_mergeFactor [g_fillCenter]")
("syGetAlignmentConstraint" "d_cvId [?object d_objId] [?direction s_direction]")
("syGetAutoJog" "d_CVId")
("syGetBottomAbutted" "d_CVId")
("syGetDimensions" "d_inputCVId")
("syGetEnv" "t_name")
("syGetFixLowLeftBoundary" "d_CVId")
("syGetForceChildCellCompact" "d_CVId")
("syGetHardCell" "d_inputCVId")
("syGetInitialDirection" "d_CVId")
("syGetLeftAbutted" "d_CVId")
("syGetMagneticConstraint" "d_cvId [?object d_objId] [?direction s_direction]")
("syGetMaxAutoJogs" "d_CVId")
("syGetMaxIterations" "d_CVId")
("syGetPFrame" "d_CVId")
("syGetPeelbackDistance" "d_CVId")
("syGetPostProcess" "d_CVId")
("syGetPreserveCellRow" "d_CVId")
("syGetPreserveWireWidth" "d_CVId")
("syGetRightAbutted" "d_CVId")
("syGetSeparationConstraint" "d_cvId [?object d_objId] [?direction s_direction]")
("syGetTopAbutted" "d_CVId")
("syGetUseChildBdy" "d_CVId")
("syGetUserConstraint" "d_cvId [?object d_objId] [?direction s_direction]")
("syGetWireJogConstraint" "d_cvId [?object d_objId] [?direction s_direction]")
("syGetWireWidthConstraint" "d_cvId [?object d_objId] [?direction s_direction]")
("syGetXAnchorBoundary" "d_CVId")
("syGetXPinGrid" "d_CVId")
("syGetXPinGridOffset" "d_CVId")
("syGetYAnchorBoundary" "d_CVId")
("syGetYPinGrid" "d_CVId")
("syGetYPinGridOffset" "d_CVId")
("syReadAlignmentConstraint" "d_constraint")
("syReadMagneticConstraint" "d_constraint")
("syReadSeparationConstraint" "d_constraint")
("syReadWireJogConstraint" "d_constraint")
("syReadWireWidthConstraint" "d_constraintId")
("syRefCellConstraint" "d_srcCvId d_destCvId")
("syRefEdgeConstraint" "l_srcEdge l_destEdge")
("sySetAutoJog" "d_CVId g_yesOrNo")
("sySetAutoJogByLayer" "d_cvId g_layer g_yesOrNo")
("sySetAutoJogByNet" "d_netId g_yesOrNo")
("sySetAutoJogByWire" "d_wireId g_yesOrNo")
("sySetBottomAbutted" "d_CVId g_yesOrNo")
("sySetEnv" "t_name g_value")
("sySetFixLowLeftBoundary" "d_CVId g_value")
("sySetForceChildCellCompact" "d_CVId g_value")
("sySetHardCell" "d_inputCVId g_yesOrNo")
("sySetInitialDirection" "d_CVId t_XOrY")
("sySetLeftAbutted" "d_CVId g_yesOrNo")
("sySetMaxAutoJogs" "d_CVId n_value")
("sySetMaxIterations" "d_CVId n_maxIter [n_minChange]")
("sySetPFrame" "d_CVId t_viewName")
("sySetPeelbackDistance" "d_CVId n_distance")
("sySetPostProcess" "d_CVId t_WlmEnum")
("sySetPreserveCellRow" "d_CVId g_yesOrNo")
("sySetPreserveWireWidth" "d_CVId g_yesOrNo")
("sySetRightAbutted" "d_CVId g_yesOrNo")
("sySetTopAbutted" "d_CVId g_yesOrNo")
("sySetUseChildBdy" "d_CVId g_yesOrNo")
("sySetXAnchorBoundary" "d_CVId g_yesOrNo")
("sySetXPinGrid" "d_CVId f_gridValue")
("sySetXPinGridOffset" "d_CVId f_gridOffsetValue")
("sySetYAnchorBoundary" "d_CVId g_yesOrNo")
("sySetYPinGrid" "d_CVId f_gridValue")
("sySetYPinGridOffset" "d_CVId f_gridOffsetValue")
("sySymToPolygon" "d_inputCVId l_outputCVName")
("syUserAllDel" "d_CVId")
("syUserAllOff" "d_CVId")
("syUserAllOn" "d_CVId")
("syUserAllXDel" "d_CVId")
("syUserAllXOff" "d_CVId")
("syUserAllXOn" "d_CVId")
("syUserAllYDel" "d_CVId")
("syUserAllYOff" "d_CVId")
("syUserAllYOn" "d_CVId")
))
