(put 'tc_funs 'symbol-type "technology file fun")
(setq tc_funs '(
("tcCreateDeviceClass" "t_viewName t_className 	[((S_classParameter g_cpValue" "Defines a class of devices.")
("tcCreateDisplay" "t_displayName l_tableSizes" "Defines a system display device for design output. The display is created in the active library.")
("tcCreateLayer" "l_layerPurpose t_layerName" "Creates a layer name to use in the open library.")
("tcDeclareDevice" "t_viewName t_className t_deviceName [((S_classParameter g_cpValue" "Creates a device in an existing device class.")
("tcDeclareWire" "t_wireName ltx_wireLayer g_defaultWidth g_minWidth g_maxWidth l_encLayerPair" "Declares a wire.")
("tcDeleteLayer" "d_layerId" "Deletes a layer.")
("tcDeleteLayerProp" "ltx_layerPurpose t_name" "Deletes a layer property.")
("tcDeleteLibProp" "t_name" "Deletes a library property.")
("tcDeleteTwoLayerProp" "ltx_layerPurpose1 ltx_layerPurpose2 t_name" "Deletes a two-layer property.")
("tcDeleteViewProp" "t_view t_name" "Deletes a view property.")
("tcDumpTechFile" "t_libraryName t_fileName [t_mode]" "Dumps the technology data for a library into an ASCII file.")
("tcGetColor" "d_displayId g_color" "Returns the red, green, and blue (RGB) components for a color and display ID.")
("tcGetDeviceCParam" "t_ViewName t_deviceName[d_libraryId]" "Returns the names and default values of the class parameters defined for a device.")
("tcGetDeviceCellView" "t_viewName t_deviceName [d_libraryId]" "Returns a dbObject ID corresponding to the supermaster cellview created for a device specified. Also opens the cellview.")
("tcGetDeviceClass" "t_viewName [t_deviceName] [d_libraryId]" "Returns the names of all device classes defined with the specified view name.")
("tcGetDeviceClassProp" "t_viewName t_deviceClassName t_propName [d_libraryId]" "Retrieves a device class technology property from the device class with the specified view name.")
("tcGetDeviceFParam" "t_viewName t_deviceName [d_libraryId]" "Returns the formal parameter names and their default values for a device.")
("tcGetDeviceInClass" "t_viewName t_className [d_libraryId]" "Returns the names of all devices in a class and view that are declared in the current technology file.")
("tcGetDeviceProp" "t_viewName t_deviceName t_propName [d_libraryId]" "Retrieves a device technology property from a device.")
("tcGetDisplay" "t_displayName [d_libraryId]" "Returns the display ID of a display device.")
("tcGetLayer" "ltx_layerPurpose [d_libraryId]" "Returns the layer ID of a layer.")
("tcGetLayerAttr" "d_layerId" "Returns the layer attributes for a layer.")
("tcGetLayerDisplay" "d_layerId d_displayId" "Returns layer display parameters as a list of indices.")
("tcGetLayerDisplayName" "d_layerId d_displayId" "Returns layer display parameters as a list of names.")
("tcGetLayerName" "x_layerNumber d_libraryId" "Returns a layer name.")
("tcGetLayerNum" "t_layerName [d_libraryId]" "Returns a layer number.")
("tcGetLayerProp" "ltx_layerPurpose t_name [d_libraryId]" "Retrieves a layer technology property.")
("tcGetLibId" "" "Returns the ID of the active library.")
("tcGetLibProp" "t_name [d_libraryId]" "Retrieves a library technology property.")
("tcGetLineStyle" "d_displayId tx_lineStyle" "Returns the line style width and pattern as a list for the specified line style and display ID.")
("tcGetPurposeName" "x_purposeNumber [d_libId]" "Returns the purpose name for the purpose number you specify.")
("tcGetPurposeNum" "t_purposeName [d_libId]" "Returns the purpose number for the purpose name you specify.")
("tcGetStipple" "d_displayId xt_stipple" "Returns the stipple pattern for a stipple and display ID.")
("tcGetTimeStamp" "[d_libraryId]" "Returns the time stamp as an integer of seconds elapsed since 00:00:00 GMT, January 1, 1990.")
("tcGetTwoLayerProp" "ltx_layerPurpose1 ltx_layerPurpose2 t_name [d_libraryId]" "Retrieves the double-layer technology properties for a layer pair.")
("tcGetViewProp" "t_view t_name [d_libraryId]" "Retrieves a view technology property.")
("tcGetWire" "g_wireName [d_libraryId]" "Returns wire information. If a wire name is specified, returns the layer purpose, minimum, maximum, default width, and enclosure layer (if any) for that wire. If nil is specified, displays a list of all wire names defined for a library.")
("tcGetWireProp" "t_wireName t_propName[d_libraryId]" "Returns the value of a property for the specified wire.")
("tcIsDevice" "d_cellViewId" "Returns t if the cellview ID is a device, nil otherwise.")
("tcLoadTechFile" "d_libraryId t_sourceFile" "Loads an ASCII source file into a library, compiling it into the library's technology data.")
("tcMakeColor" "d_displayId t_colorName l_colorAttributes x_colorIndex" "Adds a new color to the color table of a display.")
("tcMakeLineStyle" "d_displayId t_lineStyleName l_lineStyleAttributes x_lineStyleIndex" "Adds a line style to the line style table of a display.")
("tcMakeStipple" "d_displayId t_stippleName l_stipplePattern x_stippleIndex" "Adds a new stipple to the stipple table of a display.")
("tcRegPostDumpTrigger" "s_function [x_priority]" "Registers a trigger function that the system calls after dumping a technology file.")
("tcRegPostLoadTrigger" "s_function [x_priority]" "Registers a trigger function that the system calls after loading a technology file.")
("tcRegPreDumpTrigger" "s_function[ x_priority]" "Registers a trigger function that the system calls before dumping a technology file.")
("tcRegPreLoadTrigger" "s_function [x_priority]" "Registers a trigger function that the system calls before loading a technology file.")
("tcSaveTech" "d_libraryId" "Saves the technology file to disk.")
("tcSetDeviceClassProp" "t_viewName t_deviceClassName l_propertyValue" "Creates a device class technology property or resets its value.")
("tcSetDeviceProp" "t_viewName t_deviceName l_propertyValue" "Creates a device technology property or resets its value.")
("tcSetLayerAttr" "d_layerId l_layerAttributes" "Sets the layer attributes for a layer.")
("tcSetLayerDisplay" "d_layerId d_displayId l_displayAttributes" "Sets the layer display attributes for a layer and display device.")
("tcSetLayerProp" "ltx_layerPurpose l_propertyValue" "Creates a new layer property or resets the value of an existing layer property.")
("tcSetLibProp" "t_name g_expression" "Creates a library technology property or resets its value to the value of the expression.")
("tcSetPurposeName" "x_purposeNumber t_purposeName" "Assigns a new name to a purpose or changes a name.")
("tcSetTwoLayerProp" "ltx_layerPurpose1 ltx_layerPurpose2 l_propertyValue" "Creates a new two-layer property or changes the value of an existing two-layer property.")
("tcSetUserDisplayPref" "t_techfile t_libName [g_libPath]" "Sets the colors, line styles, and stipple patterns of the layers that you see when you open cellviews belonging to a library.")
("tcSetViewProp" "t_view l_propertyValue" "Creates a view technology property or resets its value.")
("tcUnregPostDumpTrigger" "s_function" "Unregisters a trigger function that the system calls after dumping a technology file so that the function is no longer called.")
("tcUnregPostLoadTrigger" "s_function" "Unregisters a trigger function that the system calls after loading a technology file so that the function is no longer called.")
("tcUnregPreDumpTrigger" "s_function" "Unregisters a trigger function that the system calls before dumping a technology file so that the function is no longer called.")
("tcUnregPreLoadTrigger" "s_function" "Unregisters a trigger function that the system calls before loading a technology file so that the function is no longer called.")
))
