function handle = putBtn(pos, string, callback, parent);

%
%
% (c) jjwikner, MERC
%

btnfldwid = 0.2;
btnfldhgt = 0.1;
bkgclr = [0.2 0.7 0.5];


if length(pos) > 2
  btnfldwid = pos(3);
end;
if length(pos) > 3
  btnfldhgt = pos(4);
end;

if (nargin == 4)
  handle = uicontrol('Parent',parent, ...
      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'HorizontalAlignment','center', ...
      'ListboxTop',0, ...
      'Position',[pos(1) pos(2) btnfldwid btnfldhgt], ...
      'Callback', callback, ...
      'String',string, ...
      'Style','pushbutton', ...
      'Tag',string);
else
  handle = uicontrol(      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'HorizontalAlignment','center', ...
      'ListboxTop',0, ...
      'Position',[pos(1) pos(2) btnfldwid btnfldhgt], ...
      'Callback', callback, ...
      'String',string, ...
      'Style','pushbutton', ...
      'Tag',string);
end;
