function handle = putChk(pos, string, callback, parent);

%
%
% (c) jjwikner, MERC
%

chkfldwid = 0.2;
chkfldhgt = 0.1;
bkgclr = [0.7 0.4 0.5];


if length(pos) > 2
  chkfldwid = pos(3);
end;
if length(pos) > 3
  chkfldhgt = pos(4);
end;


if (nargin == 4)
  handle = uicontrol('Parent',parent, ...
      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'Callback', callback, ...
      'ListboxTop',0, ...
      'Position',[pos(1) pos(2) chkfldwid chkfldhgt], ...
      'String',string, ...
      'Style','checkbox', ...
      'Tag',string, ...
      'Value',1);
else
  handle = uicontrol(      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'Callback', callback, ...
      'ListboxTop',0, ...
      'Position',[pos(1) pos(2) chkfldwid chkfldhgt], ...
      'String',string, ...
      'Style','checkbox', ...
      'Tag',string, ...
      'Value',1);
end;
