function handle = putFld(pos, string, callback, parent);
% putFld(pos, string, callback, parent)
%
% places a text ...
%
% (c) jjwikner, MERC
%

txtfldwid = 0.2;
txtfldhgt = 0.1;
bkgclr = [1 1 1];

if length(pos) > 2
  txtfldwid = pos(3);
end;
if length(pos) > 3
  txtfldhgt = pos(4);
end;

if (nargin == 4)
  handle = uicontrol('Parent',parent, ...
      'Units','normalized', ...
      'BackgroundColor', bkgclr, ...
      'HorizontalAlignment','center', ...
      'CallBack', callback, ...
      'ListboxTop',0, ...
      'Position', [pos(1) pos(2) txtfldwid txtfldhgt], ...
      'String', string,...
      'Style','edit', ...
      'Tag',string);
else
  handle = uicontrol('Units','normalized', ...
      'BackgroundColor', bkgclr, ...
      'CallBack', callback, ...
      'HorizontalAlignment','center', ...
      'ListboxTop',0, ...
      'Position', [pos(1) pos(2) txtfldwid txtfldhgt], ...
      'String', string,...
      'Style','edit', ...
      'Tag',string);
end;

