function handle = putFgr(pos, string, parent);

%
%
% (c) jjwikner, MERC
%

txtfldwid = 0.2;
txtfldhgt = 0.1;
bkgclr = [1 1 .9];
headercolor = [0 0 0];
headerweight = 'bold';
headersize = 12;

if length(pos) > 2
  txtfldwid = pos(3);
end;
if length(pos) > 3
  txtfldhgt = pos(4);
end;

if (nargin == 4)
  handle = uicontrol('Parent',parent, ...
      'Units','normalized', ...
      'BackgroundColor', bkgclr, ...
      'ListboxTop',0, ...
      'Position', [pos(1) pos(2) txtfldwid txtfldhgt], ...
      'Style','frame', ...
      'Tag',string, ...
      'Style', 'text', ...
      'String', string, ... 
      'ForegroundColor', headercolor, ...
      'FontWeight', headerweight,...
      'FontSize', headersize,...
      'Tag',string);
else
  handle = uicontrol('Units','normalized', ...
      'BackgroundColor', bkgclr, ...
      'ListboxTop',0, ...
      'Position', [pos(1) pos(2) txtfldwid txtfldhgt], ...
      'Style','frame', ...
      'Tag',string, ...
      'Style', 'text', ...
      'String', string, ... 
      'ForegroundColor', headercolor, ...
      'FontWeight', headerweight,...
      'FontSize', headersize,...
      'Tag',string);
end;
    

