function handle = putMnu(pos, string, callback, parent);

%
%
% (c) jjwikner, MERC
%

mnufldwid = 0.2;
mnufldhgt = 0.1;
bkgclr = [0.2 0.9 0.5];


if length(pos) > 2
  mnufldwid = pos(3);
end;
if length(pos) > 3
  mnufldhgt = pos(4);
end;

if (nargin == 4)
  handle = uicontrol('Parent',parent, ...
      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'ListboxTop',0, ...
      'Callback', callback, ...
      'Min',1, ...
      'Position',[pos(1) pos(2) mnufldwid mnufldhgt], ...
      'String',string, ...
      'Style','popupmenu', ...
      'Tag',string, ...
      'Value',1);
else
  handle = uicontrol('Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'ListboxTop',0, ...
      'Min',1, ...
      'Callback', callback, ...
      'Position',[pos(1) pos(2) mnufldwid mnufldhgt], ...
      'String',string, ...
      'Style','popupmenu', ...
      'Tag',string, ...
      'Value',1);

end;
