function handle = putRdo(pos, string, callback, parent);

%
%
% (c) jjwikner, MERC
%

rdofldwid = 0.2;
rdofldhgt = 0.1;
bkgclr = [0.7 0.2 0.5];


if length(pos) > 2
  rdofldwid = pos(3);
end;
if length(pos) > 3
  rdofldhgt = pos(4);
end;

if (nargin == 4)
  handle = uicontrol('Parent',parent, ...
      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'Callback', callback, ...
      'ListboxTop',0, ...
      'Position',[pos(1) pos(2) rdofldwid rdofldhgt], ...
      'String', string, ...
      'Style','radiobutton', ...
      'Tag',string, ...
      'Value',1);
else
  handle = uicontrol(      'Units','normalized', ...
      'BackgroundColor',bkgclr, ...
      'Callback', callback, ...
      'ListboxTop',0, ...
      'Position',[pos(1) pos(2) rdofldwid rdofldhgt], ...
      'String', string, ...
      'Style','radiobutton', ...
      'Tag',string, ...
      'Value',1);
end;
