/** 79447139 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "daisySimDigToVolt_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int daisySimDigToVolt_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_vgnd_168 = 0.0;
_Static_d_by_dv_sigin_vgnd_128 = 0.0;
_Static_d_by_dv_vpwr_vgnd_144 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 23);ahdlDoSetLineNum ((long) 23);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vpwr_36, _vgnd_28)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_supply_val_88) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 24);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_supply_val_88) * ((getAcrossSolution2(_sigin_20, _vgnd_28))))));__tmpStkVar_3 = ((((__tmpStkVar_1)) * (((getAcrossSolution2(_sigin_20, _vgnd_28))))));__tmpStkVar_2 = (_supply_val_88);(_sigout_val_48) = __tempValueResultStatic;}if (((_sigout_val_48) > (_supply_val_88))){{ahdlDoSetLineNum ((long) 27);ahdlDoSetLineNum ((long) 27);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_supply_val_88);__tmpStkVar_3 = (__tmpStkVar_1);__tmpStkVar_2 = 0.0;(_sigout_val_48) = __tempValueResultStatic;}}}if (((_sigout_val_48) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((0L));__tmpStkVar_3 = 0.0;__tmpStkVar_2 = 0.0;(_sigout_val_48) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 34);(_V_Static_sigout_vgnd_168) += (_sigout_val_48);_Static_d_by_dv_sigin_vgnd_128 += (__tmpStkVar_2);_Static_d_by_dv_vpwr_vgnd_144 += (__tmpStkVar_3);}ahdlDoSetLineNum ((long) 35);    ahdlInterSetAcrossQuan(      *(void **)(instData + 156),
       _sigout_12,       _vgnd_28,       _sigout_vgnd_flow_152,      _V_Static_sigout_vgnd_168   ,       1.0    );
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 124), _Static_d_by_dv_sigin_vgnd_128);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 120), -_Static_d_by_dv_sigin_vgnd_128);
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 140), _Static_d_by_dv_vpwr_vgnd_144);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 136), -_Static_d_by_dv_vpwr_vgnd_144);
    return __msgSeverity__;
} /** end of daisySimDigToVolt_DcFuncDerLoad **/

int daisySimDigToVolt_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_vgnd_168 = 0.0;
_Static_d_by_dv_sigin_vgnd_128 = 0.0;
_Static_d_by_dv_vpwr_vgnd_144 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 23);ahdlDoSetLineNum ((long) 23);(_supply_val_88) = ((getAcrossSolution2(_vpwr_36, _vgnd_28)));ahdlDoSetLineNum ((long) 24);(_sigout_val_48) = ((((_supply_val_88) * ((getAcrossSolution2(_sigin_20, _vgnd_28))))));if (((_sigout_val_48) > (_supply_val_88))){{ahdlDoSetLineNum ((long) 27);ahdlDoSetLineNum ((long) 27);(_sigout_val_48) = (_supply_val_88);}}if (((_sigout_val_48) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);(_sigout_val_48) = __INT_TO_DBL((0L));}}ahdlDoSetLineNum ((long) 34);(_V_Static_sigout_vgnd_168) += (_sigout_val_48);}ahdlDoSetLineNum ((long) 35);    ahdlInterSetAcrossQuan(      *(void **)(instData + 156),
       _sigout_12,       _vgnd_28,       _sigout_vgnd_flow_152,      _V_Static_sigout_vgnd_168   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimDigToVolt_DcFuncLoad **/

int daisySimDigToVolt_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_vgnd_168 = 0.0;
_Static_d_by_dv_sigin_vgnd_128 = 0.0;
_Static_d_by_dv_vpwr_vgnd_144 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 23);ahdlDoSetLineNum ((long) 23);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vpwr_36, _vgnd_28)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_supply_val_88) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 24);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_supply_val_88) * ((getAcrossSolution2(_sigin_20, _vgnd_28))))));__tmpStkVar_3 = ((((__tmpStkVar_1)) * (((getAcrossSolution2(_sigin_20, _vgnd_28))))));__tmpStkVar_2 = (_supply_val_88);(_sigout_val_48) = __tempValueResultStatic;}if (((_sigout_val_48) > (_supply_val_88))){{ahdlDoSetLineNum ((long) 27);ahdlDoSetLineNum ((long) 27);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_supply_val_88);__tmpStkVar_3 = (__tmpStkVar_1);__tmpStkVar_2 = 0.0;(_sigout_val_48) = __tempValueResultStatic;}}}if (((_sigout_val_48) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((0L));__tmpStkVar_3 = 0.0;__tmpStkVar_2 = 0.0;(_sigout_val_48) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 34);(_V_Static_sigout_vgnd_168) += (_sigout_val_48);_Static_d_by_dv_sigin_vgnd_128 += (__tmpStkVar_2);_Static_d_by_dv_vpwr_vgnd_144 += (__tmpStkVar_3);}ahdlDoSetLineNum ((long) 35);    ahdlInterSetAcrossQuan(      *(void **)(instData + 156),
       _sigout_12,       _vgnd_28,       _sigout_vgnd_flow_152,      _V_Static_sigout_vgnd_168   ,       1.0    );
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 124), _Static_d_by_dv_sigin_vgnd_128);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 120), -_Static_d_by_dv_sigin_vgnd_128);
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 140), _Static_d_by_dv_vpwr_vgnd_144);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 136), -_Static_d_by_dv_vpwr_vgnd_144);
    return __msgSeverity__;
} /** end of daisySimDigToVolt_TranFuncDerLoad **/

int daisySimDigToVolt_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_vgnd_168 = 0.0;
_Static_d_by_dv_sigin_vgnd_128 = 0.0;
_Static_d_by_dv_vpwr_vgnd_144 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 23);ahdlDoSetLineNum ((long) 23);(_supply_val_88) = ((getAcrossSolution2(_vpwr_36, _vgnd_28)));ahdlDoSetLineNum ((long) 24);(_sigout_val_48) = ((((_supply_val_88) * ((getAcrossSolution2(_sigin_20, _vgnd_28))))));if (((_sigout_val_48) > (_supply_val_88))){{ahdlDoSetLineNum ((long) 27);ahdlDoSetLineNum ((long) 27);(_sigout_val_48) = (_supply_val_88);}}if (((_sigout_val_48) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 31);ahdlDoSetLineNum ((long) 31);(_sigout_val_48) = __INT_TO_DBL((0L));}}ahdlDoSetLineNum ((long) 34);(_V_Static_sigout_vgnd_168) += (_sigout_val_48);}ahdlDoSetLineNum ((long) 35);    ahdlInterSetAcrossQuan(      *(void **)(instData + 156),
       _sigout_12,       _vgnd_28,       _sigout_vgnd_flow_152,      _V_Static_sigout_vgnd_168   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimDigToVolt_TranFuncLoad **/

int daisySimDigToVolt_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of daisySimDigToVolt_NoiseLoadBiasDep **/

int daisySimDigToVolt_OpPointCalc(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
    return __msgSeverity__;
} /** end of daisySimDigToVolt_OpPointCalc **/

