function windowname = cFunctionnames(windowtype);

WINDOWNAMES = [	'Rectangular';	...
		'  Hamming  ';	...
		'  Hanning  ';	...
		'Triangular ';	...
		' Bartlett  ';	...
		' Gaussian  ';	...
		' Blackman  ';	...
		'  Kaiser   ';	...
		' Chebyshev '];

windowname = mat2str(WINDOWNAMES(windowtype,:));
