/** 2920311907 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "daisySimSignalLim_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int daisySimSignalLim_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_sigoutN_176 = 0.0;
_Static_d_by_dv_sigin_vgnd_136 = 0.0;
_Static_d_by_dv_vpwr_vgnd_152 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 21);ahdlDoSetLineNum ((long) 21);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_sigin_28, _vgnd_36)));__tmpStkVar_3 = 0.0;__tmpStkVar_1 = ((1.00000000000000000000e+00));(_sigout_val_56) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 22);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vpwr_44, _vgnd_36)));__tmpStkVar_2 = ((1.00000000000000000000e+00));(_supply_val_96) = __tempValueResultStatic;}if (((_sigout_val_56) > (_supply_val_96))){{ahdlDoSetLineNum ((long) 25);ahdlDoSetLineNum ((long) 25);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_supply_val_96);__tmpStkVar_3 = (__tmpStkVar_2);__tmpStkVar_1 = 0.0;(_sigout_val_56) = __tempValueResultStatic;}}}if (((_sigout_val_56) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 29);ahdlDoSetLineNum ((long) 29);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((0L));__tmpStkVar_3 = 0.0;__tmpStkVar_1 = 0.0;(_sigout_val_56) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 32);(_V_Static_sigout_sigoutN_176) += (_sigout_val_56);_Static_d_by_dv_sigin_vgnd_136 += (__tmpStkVar_1);_Static_d_by_dv_vpwr_vgnd_152 += (__tmpStkVar_3);}ahdlDoSetLineNum ((long) 33);    ahdlInterSetAcrossQuan(      *(void **)(instData + 164),
       _sigout_12,       _sigoutN_20,       _sigout_sigoutN_flow_160,      _V_Static_sigout_sigoutN_176   ,       1.0    );
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 132), _Static_d_by_dv_sigin_vgnd_136);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 128), -_Static_d_by_dv_sigin_vgnd_136);
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 148), _Static_d_by_dv_vpwr_vgnd_152);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 144), -_Static_d_by_dv_vpwr_vgnd_152);
    return __msgSeverity__;
} /** end of daisySimSignalLim_DcFuncDerLoad **/

int daisySimSignalLim_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_sigoutN_176 = 0.0;
_Static_d_by_dv_sigin_vgnd_136 = 0.0;
_Static_d_by_dv_vpwr_vgnd_152 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 21);ahdlDoSetLineNum ((long) 21);(_sigout_val_56) = ((getAcrossSolution2(_sigin_28, _vgnd_36)));ahdlDoSetLineNum ((long) 22);(_supply_val_96) = ((getAcrossSolution2(_vpwr_44, _vgnd_36)));if (((_sigout_val_56) > (_supply_val_96))){{ahdlDoSetLineNum ((long) 25);ahdlDoSetLineNum ((long) 25);(_sigout_val_56) = (_supply_val_96);}}if (((_sigout_val_56) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 29);ahdlDoSetLineNum ((long) 29);(_sigout_val_56) = __INT_TO_DBL((0L));}}ahdlDoSetLineNum ((long) 32);(_V_Static_sigout_sigoutN_176) += (_sigout_val_56);}ahdlDoSetLineNum ((long) 33);    ahdlInterSetAcrossQuan(      *(void **)(instData + 164),
       _sigout_12,       _sigoutN_20,       _sigout_sigoutN_flow_160,      _V_Static_sigout_sigoutN_176   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimSignalLim_DcFuncLoad **/

int daisySimSignalLim_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_sigoutN_176 = 0.0;
_Static_d_by_dv_sigin_vgnd_136 = 0.0;
_Static_d_by_dv_vpwr_vgnd_152 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 21);ahdlDoSetLineNum ((long) 21);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_sigin_28, _vgnd_36)));__tmpStkVar_3 = 0.0;__tmpStkVar_1 = ((1.00000000000000000000e+00));(_sigout_val_56) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 22);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vpwr_44, _vgnd_36)));__tmpStkVar_2 = ((1.00000000000000000000e+00));(_supply_val_96) = __tempValueResultStatic;}if (((_sigout_val_56) > (_supply_val_96))){{ahdlDoSetLineNum ((long) 25);ahdlDoSetLineNum ((long) 25);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_supply_val_96);__tmpStkVar_3 = (__tmpStkVar_2);__tmpStkVar_1 = 0.0;(_sigout_val_56) = __tempValueResultStatic;}}}if (((_sigout_val_56) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 29);ahdlDoSetLineNum ((long) 29);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((0L));__tmpStkVar_3 = 0.0;__tmpStkVar_1 = 0.0;(_sigout_val_56) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 32);(_V_Static_sigout_sigoutN_176) += (_sigout_val_56);_Static_d_by_dv_sigin_vgnd_136 += (__tmpStkVar_1);_Static_d_by_dv_vpwr_vgnd_152 += (__tmpStkVar_3);}ahdlDoSetLineNum ((long) 33);    ahdlInterSetAcrossQuan(      *(void **)(instData + 164),
       _sigout_12,       _sigoutN_20,       _sigout_sigoutN_flow_160,      _V_Static_sigout_sigoutN_176   ,       1.0    );
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 132), _Static_d_by_dv_sigin_vgnd_136);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 128), -_Static_d_by_dv_sigin_vgnd_136);
      /* do positive component */      ahdlInterAddStaticElement(*(void**)(instData + 148), _Static_d_by_dv_vpwr_vgnd_152);
      /* do negative component */      ahdlInterAddStaticElement(*(void**)(instData + 144), -_Static_d_by_dv_vpwr_vgnd_152);
    return __msgSeverity__;
} /** end of daisySimSignalLim_TranFuncDerLoad **/

int daisySimSignalLim_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_V_Static_sigout_sigoutN_176 = 0.0;
_Static_d_by_dv_sigin_vgnd_136 = 0.0;
_Static_d_by_dv_vpwr_vgnd_152 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 21);ahdlDoSetLineNum ((long) 21);(_sigout_val_56) = ((getAcrossSolution2(_sigin_28, _vgnd_36)));ahdlDoSetLineNum ((long) 22);(_supply_val_96) = ((getAcrossSolution2(_vpwr_44, _vgnd_36)));if (((_sigout_val_56) > (_supply_val_96))){{ahdlDoSetLineNum ((long) 25);ahdlDoSetLineNum ((long) 25);(_sigout_val_56) = (_supply_val_96);}}if (((_sigout_val_56) < __INT_TO_DBL((0L)))){{ahdlDoSetLineNum ((long) 29);ahdlDoSetLineNum ((long) 29);(_sigout_val_56) = __INT_TO_DBL((0L));}}ahdlDoSetLineNum ((long) 32);(_V_Static_sigout_sigoutN_176) += (_sigout_val_56);}ahdlDoSetLineNum ((long) 33);    ahdlInterSetAcrossQuan(      *(void **)(instData + 164),
       _sigout_12,       _sigoutN_20,       _sigout_sigoutN_flow_160,      _V_Static_sigout_sigoutN_176   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimSignalLim_TranFuncLoad **/

int daisySimSignalLim_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of daisySimSignalLim_NoiseLoadBiasDep **/

int daisySimSignalLim_OpPointCalc(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
    return __msgSeverity__;
} /** end of daisySimSignalLim_OpPointCalc **/

