/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include "ahdlcmi.h"

int ahdlBsourceInterfaceVersion() {
   return 1; /* Only used when version >= spectre's BsourceInterfaceVersion */
}

extern int daisySimSupply_DcFuncDerLoad(int, char*, char*, char**);
extern int daisySimSupply_DcFuncLoad(int, char*, char*, char**);
extern int daisySimSupply_TranFuncDerLoad(int, char*, char*, char**);
extern int daisySimSupply_TranFuncLoad(int, char*, char*, char**);
extern int daisySimSupply_NoiseLoadBiasDep(int, char*, char*, char**);
extern int daisySimSupply_OpPointCalc(int, char*, char*, char**);

int daisySimSupply_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        daisySimSupply_DcFuncDerLoad,  
                        daisySimSupply_DcFuncLoad,     
                        daisySimSupply_TranFuncDerLoad,
                        daisySimSupply_TranFuncLoad,   
                        daisySimSupply_NoiseLoadBiasDep,
                        daisySimSupply_OpPointCalc
                       );
   return 1; /** success **/
}
extern int siconSupply_DcFuncDerLoad(int, char*, char*, char**);
extern int siconSupply_DcFuncLoad(int, char*, char*, char**);
extern int siconSupply_TranFuncDerLoad(int, char*, char*, char**);
extern int siconSupply_TranFuncLoad(int, char*, char*, char**);
extern int siconSupply_NoiseLoadBiasDep(int, char*, char*, char**);
extern int siconSupply_OpPointCalc(int, char*, char*, char**);

int siconSupply_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        siconSupply_DcFuncDerLoad,  
                        siconSupply_DcFuncLoad,     
                        siconSupply_TranFuncDerLoad,
                        siconSupply_TranFuncLoad,   
                        siconSupply_NoiseLoadBiasDep,
                        siconSupply_OpPointCalc
                       );
   return 1; /** success **/
}
