/** 269323702 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "siconSupply_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int siconSupply_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_312 = 0.0;
_V_Static_vpwr10dig_vgnd_344 = 0.0;
_V_Static_vpwr33ana_vgnd_376 = 0.0;
_V_Static_vpwr33dig_vgnd_408 = 0.0;
_V_Static_vgnd_440 = 0.0;
_V_Static_vsub_472 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10ana_vgnd_312) += (_power10_232);ahdlDoSetLineNum ((long) 33);(_V_Static_vpwr10dig_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33ana_vgnd_376) += (_power33_280);ahdlDoSetLineNum ((long) 36);(_V_Static_vpwr33dig_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 38);(_V_Static_vgnd_440) += __INT_TO_DBL ((0L));ahdlDoSetLineNum ((long) 39);(_V_Static_vsub_472) += __INT_TO_DBL ((0L));}ahdlDoSetLineNum ((long) 41);    ahdlInterSetAcrossQuan(      *(void **)(instData + 300),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_296,      _V_Static_vpwr10ana_vgnd_312   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_328,      _V_Static_vpwr10dig_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_360,      _V_Static_vpwr33ana_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_392,      _V_Static_vpwr33dig_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_424,      _V_Static_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_456,      _V_Static_vsub_472   ,       1.0    );
    return __msgSeverity__;
} /** end of siconSupply_DcFuncDerLoad **/

int siconSupply_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_312 = 0.0;
_V_Static_vpwr10dig_vgnd_344 = 0.0;
_V_Static_vpwr33ana_vgnd_376 = 0.0;
_V_Static_vpwr33dig_vgnd_408 = 0.0;
_V_Static_vgnd_440 = 0.0;
_V_Static_vsub_472 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10ana_vgnd_312) += (_power10_232);ahdlDoSetLineNum ((long) 33);(_V_Static_vpwr10dig_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33ana_vgnd_376) += (_power33_280);ahdlDoSetLineNum ((long) 36);(_V_Static_vpwr33dig_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 38);(_V_Static_vgnd_440) += __INT_TO_DBL ((0L));ahdlDoSetLineNum ((long) 39);(_V_Static_vsub_472) += __INT_TO_DBL ((0L));}ahdlDoSetLineNum ((long) 41);    ahdlInterSetAcrossQuan(      *(void **)(instData + 300),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_296,      _V_Static_vpwr10ana_vgnd_312   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_328,      _V_Static_vpwr10dig_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_360,      _V_Static_vpwr33ana_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_392,      _V_Static_vpwr33dig_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_424,      _V_Static_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_456,      _V_Static_vsub_472   ,       1.0    );
    return __msgSeverity__;
} /** end of siconSupply_DcFuncLoad **/

int siconSupply_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_312 = 0.0;
_V_Static_vpwr10dig_vgnd_344 = 0.0;
_V_Static_vpwr33ana_vgnd_376 = 0.0;
_V_Static_vpwr33dig_vgnd_408 = 0.0;
_V_Static_vgnd_440 = 0.0;
_V_Static_vsub_472 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10ana_vgnd_312) += (_power10_232);ahdlDoSetLineNum ((long) 33);(_V_Static_vpwr10dig_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33ana_vgnd_376) += (_power33_280);ahdlDoSetLineNum ((long) 36);(_V_Static_vpwr33dig_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 38);(_V_Static_vgnd_440) += __INT_TO_DBL ((0L));ahdlDoSetLineNum ((long) 39);(_V_Static_vsub_472) += __INT_TO_DBL ((0L));}ahdlDoSetLineNum ((long) 41);    ahdlInterSetAcrossQuan(      *(void **)(instData + 300),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_296,      _V_Static_vpwr10ana_vgnd_312   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_328,      _V_Static_vpwr10dig_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_360,      _V_Static_vpwr33ana_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_392,      _V_Static_vpwr33dig_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_424,      _V_Static_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_456,      _V_Static_vsub_472   ,       1.0    );
    return __msgSeverity__;
} /** end of siconSupply_TranFuncDerLoad **/

int siconSupply_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_V_Static_vpwr10ana_vgnd_312 = 0.0;
_V_Static_vpwr10dig_vgnd_344 = 0.0;
_V_Static_vpwr33ana_vgnd_376 = 0.0;
_V_Static_vpwr33dig_vgnd_408 = 0.0;
_V_Static_vgnd_440 = 0.0;
_V_Static_vsub_472 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);(_V_Static_vpwr10ana_vgnd_312) += (_power10_232);ahdlDoSetLineNum ((long) 33);(_V_Static_vpwr10dig_vgnd_344) += (_power10_232);ahdlDoSetLineNum ((long) 35);(_V_Static_vpwr33ana_vgnd_376) += (_power33_280);ahdlDoSetLineNum ((long) 36);(_V_Static_vpwr33dig_vgnd_408) += (_power33_280);ahdlDoSetLineNum ((long) 38);(_V_Static_vgnd_440) += __INT_TO_DBL ((0L));ahdlDoSetLineNum ((long) 39);(_V_Static_vsub_472) += __INT_TO_DBL ((0L));}ahdlDoSetLineNum ((long) 41);    ahdlInterSetAcrossQuan(      *(void **)(instData + 300),
       _vpwr10ana_20,       _vgnd_12,       _vpwr10ana_vgnd_flow_296,      _V_Static_vpwr10ana_vgnd_312   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 332),
       _vpwr10dig_28,       _vgnd_12,       _vpwr10dig_vgnd_flow_328,      _V_Static_vpwr10dig_vgnd_344   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 364),
       _vpwr33ana_36,       _vgnd_12,       _vpwr33ana_vgnd_flow_360,      _V_Static_vpwr33ana_vgnd_376   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 396),
       _vpwr33dig_44,       _vgnd_12,       _vpwr33dig_vgnd_flow_392,      _V_Static_vpwr33dig_vgnd_408   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 428),
       _vgnd_12,       *(long*)(instData + 0),       _vgnd_flow_424,      _V_Static_vgnd_440   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 460),
       _vsub_52,       *(long*)(instData + 0),       _vsub_flow_456,      _V_Static_vsub_472   ,       1.0    );
    return __msgSeverity__;
} /** end of siconSupply_TranFuncLoad **/

int siconSupply_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


    return __msgSeverity__;
} /** end of siconSupply_NoiseLoadBiasDep **/

int siconSupply_OpPointCalc(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
    return __msgSeverity__;
} /** end of siconSupply_OpPointCalc **/

