/** 688811361 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef SICONSUPPLY_INST_STATIC_H
#define SICONSUPPLY_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_vsub_480	(*((double *) &instData [480]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vsub_472	(*((double *) &instData [472]))	/* Branch Reln : Size = 8 bytes. */
#define _vsub_flow_456	(*((long *) &instData [456]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_vgnd_448	(*((double *) &instData [448]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vgnd_440	(*((double *) &instData [440]))	/* Branch Reln : Size = 8 bytes. */
#define _vgnd_flow_424	(*((long *) &instData [424]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_vpwr33dig_vgnd_416	(*((double *) &instData [416]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vpwr33dig_vgnd_408	(*((double *) &instData [408]))	/* Branch Reln : Size = 8 bytes. */
#define _vpwr33dig_vgnd_flow_392	(*((long *) &instData [392]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_vpwr33ana_vgnd_384	(*((double *) &instData [384]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vpwr33ana_vgnd_376	(*((double *) &instData [376]))	/* Branch Reln : Size = 8 bytes. */
#define _vpwr33ana_vgnd_flow_360	(*((long *) &instData [360]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_vpwr10dig_vgnd_352	(*((double *) &instData [352]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vpwr10dig_vgnd_344	(*((double *) &instData [344]))	/* Branch Reln : Size = 8 bytes. */
#define _vpwr10dig_vgnd_flow_328	(*((long *) &instData [328]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_vpwr10ana_vgnd_320	(*((double *) &instData [320]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vpwr10ana_vgnd_312	(*((double *) &instData [312]))	/* Branch Reln : Size = 8 bytes. */
#define _vpwr10ana_vgnd_flow_296	(*((long *) &instData [296]))	/* Hidden Node : Size = 4 bytes. */
#define _power33_280	(*((double *) &instData [280]))	/* VT_REAL : Size = 8 bytes. */
#define _substRes_256	(*((double *) &instData [256]))	/* VT_REAL : Size = 8 bytes. */
#define _power10_232	(*((double *) &instData [232]))	/* VT_REAL : Size = 8 bytes. */
#define _ana10ResOut_208	(*((double *) &instData [208]))	/* VT_REAL : Size = 8 bytes. */
#define _ana33ResOut_184	(*((double *) &instData [184]))	/* VT_REAL : Size = 8 bytes. */
#define _dig10ResOut_160	(*((double *) &instData [160]))	/* VT_REAL : Size = 8 bytes. */
#define _dig33ResOut_136	(*((double *) &instData [136]))	/* VT_REAL : Size = 8 bytes. */
#define _globalGroundRes_112	(*((double *) &instData [112]))	/* VT_REAL : Size = 8 bytes. */
#define _tStartSupply_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _tReadySupply_64	(*((double *) &instData [64]))	/* VT_REAL : Size = 8 bytes. */
#define _vsub_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _vpwr33dig_44	(*((long *) &instData [44]))	/* VT_NODE : Size = 4 bytes. */
#define _vpwr33ana_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _vpwr10dig_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _vpwr10ana_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vgnd_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* SICONSUPPLY_INST_STATIC_H */
