/** 728796389 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DAISYPINPARASITICS_INST_STATIC_H
#define DAISYPINPARASITICS_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_vPackage_vPad_216	(*((double *) &instData [216]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_vPackage_vPad_208	(*((double *) &instData [208]))	/* Branch Reln : Size = 8 bytes. */
#define _vPackage_vPad_flow_192	(*((long *) &instData [192]))	/* Hidden Node : Size = 4 bytes. */
#define _Static_d_by_di_vPackage_vPad_184	(*((double *) &instData [184]))	/* Branch Load Group : Size = 8 bytes. */
#define _bondInd_160	(*((double *) &instData [160]))	/* VT_REAL : Size = 8 bytes. */
#define _bondRes_136	(*((double *) &instData [136]))	/* VT_REAL : Size = 8 bytes. */
#define _leadCap_112	(*((double *) &instData [112]))	/* VT_REAL : Size = 8 bytes. */
#define _leadInd_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _leadRes_64	(*((double *) &instData [64]))	/* VT_REAL : Size = 8 bytes. */
#define _padCap_40	(*((double *) &instData [40]))	/* VT_REAL : Size = 8 bytes. */
#define _vgnd_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _vPad_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vPackage_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DAISYPINPARASITICS_INST_STATIC_H */
