/** 1816703546 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "daisySimAdc_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int daisySimAdc_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */memcpy ((void *) (instData + 312), (void *) (instData + 440), 128);
_V_Static_DATA_7__592 = 0.0;
_V_Static_DATA_6__624 = 0.0;
_V_Static_DATA_5__656 = 0.0;
_V_Static_DATA_4__688 = 0.0;
_V_Static_DATA_3__720 = 0.0;
_V_Static_DATA_2__752 = 0.0;
_V_Static_DATA_1__784 = 0.0;
_V_Static_DATA_0__816 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 24);ahdlDoSetLineNum ((long) 24);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((_vLogicHigh_96), ((2.00000000000000000000e+00)))));(_vtrans_clk_240) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 25);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((0.00000000000000000000e+00));(_vlogic_low_200) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 26);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((1L));(_vref_280) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 27);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((2L)))));(_halfref_160) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 31);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution1(_vin_52)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_unconverted_120) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 32);for (_i_572 = (7L); (((_i_572)) >= ((0L))); _i_572 = (((_i_572) - ((1L))))){{ahdlDoSetLineNum ((long) 33);ahdlDoSetLineNum ((long) 33);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((0L));(_vd_312((_i_572))) = __tempValueResultStatic;}if ((((((_unconverted_120) - (_halfref_160)))) > ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((512L))))))){{ahdlDoSetLineNum ((long) 35);ahdlDoSetLineNum ((long) 35);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_vLogicHigh_96);(_vd_312((_i_572))) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 36);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_unconverted_120) - (_halfref_160))));__tmpStkVar_1 = (__tmpStkVar_1);(_unconverted_120) = __tempValueResultStatic;}}}else{{ahdlDoSetLineNum ((long) 38);ahdlDoSetLineNum ((long) 38);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_vlogic_low_200);(_vd_312((_i_572))) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 40);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_unconverted_120) * __INT_TO_DBL((2L)))));__tmpStkVar_1 = ((((__tmpStkVar_1)) * (__INT_TO_DBL((2L)))));(_unconverted_120) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 70);(_V_Static_DATA_7__592) += (_vd_312((7L)));ahdlDoSetLineNum ((long) 71);(_V_Static_DATA_6__624) += (_vd_312((6L)));ahdlDoSetLineNum ((long) 72);(_V_Static_DATA_5__656) += (_vd_312((5L)));ahdlDoSetLineNum ((long) 73);(_V_Static_DATA_4__688) += (_vd_312((4L)));ahdlDoSetLineNum ((long) 74);(_V_Static_DATA_3__720) += (_vd_312((3L)));ahdlDoSetLineNum ((long) 75);(_V_Static_DATA_2__752) += (_vd_312((2L)));ahdlDoSetLineNum ((long) 76);(_V_Static_DATA_1__784) += (_vd_312((1L)));ahdlDoSetLineNum ((long) 77);(_V_Static_DATA_0__816) += (_vd_312((0L)));}ahdlDoSetLineNum ((long) 82);    ahdlInterSetAcrossQuan(      *(void **)(instData + 584),
       _DATA_16,       *(long*)(instData + 0),       _DATA_7__flow_580,      _V_Static_DATA_7__592   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 612),
       *(long*)(instData + 20),       *(long*)(instData + 0),       _DATA_6__flow_608,      _V_Static_DATA_6__624   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 644),
       *(long*)(instData + 24),       *(long*)(instData + 0),       _DATA_5__flow_640,      _V_Static_DATA_5__656   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 676),
       *(long*)(instData + 28),       *(long*)(instData + 0),       _DATA_4__flow_672,      _V_Static_DATA_4__688   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 708),
       *(long*)(instData + 32),       *(long*)(instData + 0),       _DATA_3__flow_704,      _V_Static_DATA_3__720   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 740),
       *(long*)(instData + 36),       *(long*)(instData + 0),       _DATA_2__flow_736,      _V_Static_DATA_2__752   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 772),
       *(long*)(instData + 40),       *(long*)(instData + 0),       _DATA_1__flow_768,      _V_Static_DATA_1__784   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 804),
       *(long*)(instData + 44),       *(long*)(instData + 0),       _DATA_0__flow_800,      _V_Static_DATA_0__816   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimAdc_DcFuncDerLoad **/

int daisySimAdc_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */memcpy ((void *) (instData + 312), (void *) (instData + 440), 128);
_V_Static_DATA_7__592 = 0.0;
_V_Static_DATA_6__624 = 0.0;
_V_Static_DATA_5__656 = 0.0;
_V_Static_DATA_4__688 = 0.0;
_V_Static_DATA_3__720 = 0.0;
_V_Static_DATA_2__752 = 0.0;
_V_Static_DATA_1__784 = 0.0;
_V_Static_DATA_0__816 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 24);ahdlDoSetLineNum ((long) 24);(_vtrans_clk_240) = ((__FLOAT_DIV((_vLogicHigh_96), ((2.00000000000000000000e+00)))));ahdlDoSetLineNum ((long) 25);(_vlogic_low_200) = ((0.00000000000000000000e+00));ahdlDoSetLineNum ((long) 26);(_vref_280) = __INT_TO_DBL((1L));ahdlDoSetLineNum ((long) 27);(_halfref_160) = ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((2L)))));ahdlDoSetLineNum ((long) 31);(_unconverted_120) = ((getAcrossSolution1(_vin_52)));ahdlDoSetLineNum ((long) 32);for (_i_572 = (7L); (((_i_572)) >= ((0L))); _i_572 = (((_i_572) - ((1L))))){{ahdlDoSetLineNum ((long) 33);ahdlDoSetLineNum ((long) 33);(_vd_312((_i_572))) = __INT_TO_DBL((0L));if ((((((_unconverted_120) - (_halfref_160)))) > ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((512L))))))){{ahdlDoSetLineNum ((long) 35);ahdlDoSetLineNum ((long) 35);(_vd_312((_i_572))) = (_vLogicHigh_96);ahdlDoSetLineNum ((long) 36);(_unconverted_120) = ((((_unconverted_120) - (_halfref_160))));}}else{{ahdlDoSetLineNum ((long) 38);ahdlDoSetLineNum ((long) 38);(_vd_312((_i_572))) = (_vlogic_low_200);}}ahdlDoSetLineNum ((long) 40);(_unconverted_120) = ((((_unconverted_120) * __INT_TO_DBL((2L)))));}}ahdlDoSetLineNum ((long) 70);(_V_Static_DATA_7__592) += (_vd_312((7L)));ahdlDoSetLineNum ((long) 71);(_V_Static_DATA_6__624) += (_vd_312((6L)));ahdlDoSetLineNum ((long) 72);(_V_Static_DATA_5__656) += (_vd_312((5L)));ahdlDoSetLineNum ((long) 73);(_V_Static_DATA_4__688) += (_vd_312((4L)));ahdlDoSetLineNum ((long) 74);(_V_Static_DATA_3__720) += (_vd_312((3L)));ahdlDoSetLineNum ((long) 75);(_V_Static_DATA_2__752) += (_vd_312((2L)));ahdlDoSetLineNum ((long) 76);(_V_Static_DATA_1__784) += (_vd_312((1L)));ahdlDoSetLineNum ((long) 77);(_V_Static_DATA_0__816) += (_vd_312((0L)));}ahdlDoSetLineNum ((long) 82);    ahdlInterSetAcrossQuan(      *(void **)(instData + 584),
       _DATA_16,       *(long*)(instData + 0),       _DATA_7__flow_580,      _V_Static_DATA_7__592   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 612),
       *(long*)(instData + 20),       *(long*)(instData + 0),       _DATA_6__flow_608,      _V_Static_DATA_6__624   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 644),
       *(long*)(instData + 24),       *(long*)(instData + 0),       _DATA_5__flow_640,      _V_Static_DATA_5__656   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 676),
       *(long*)(instData + 28),       *(long*)(instData + 0),       _DATA_4__flow_672,      _V_Static_DATA_4__688   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 708),
       *(long*)(instData + 32),       *(long*)(instData + 0),       _DATA_3__flow_704,      _V_Static_DATA_3__720   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 740),
       *(long*)(instData + 36),       *(long*)(instData + 0),       _DATA_2__flow_736,      _V_Static_DATA_2__752   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 772),
       *(long*)(instData + 40),       *(long*)(instData + 0),       _DATA_1__flow_768,      _V_Static_DATA_1__784   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 804),
       *(long*)(instData + 44),       *(long*)(instData + 0),       _DATA_0__flow_800,      _V_Static_DATA_0__816   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimAdc_DcFuncLoad **/

int daisySimAdc_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */memcpy ((void *) (instData + 312), (void *) (instData + 440), 128);
_V_Static_DATA_7__592 = 0.0;
_V_Static_DATA_6__624 = 0.0;
_V_Static_DATA_5__656 = 0.0;
_V_Static_DATA_4__688 = 0.0;
_V_Static_DATA_3__720 = 0.0;
_V_Static_DATA_2__752 = 0.0;
_V_Static_DATA_1__784 = 0.0;
_V_Static_DATA_0__816 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 24);ahdlDoSetLineNum ((long) 24);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((_vLogicHigh_96), ((2.00000000000000000000e+00)))));(_vtrans_clk_240) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 25);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((0.00000000000000000000e+00));(_vlogic_low_200) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 26);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((1L));(_vref_280) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 27);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((2L)))));(_halfref_160) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 31);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution1(_vin_52)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_unconverted_120) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 32);for (_i_572 = (7L); (((_i_572)) >= ((0L))); _i_572 = (((_i_572) - ((1L))))){{ahdlDoSetLineNum ((long) 33);ahdlDoSetLineNum ((long) 33);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = __INT_TO_DBL((0L));(_vd_312((_i_572))) = __tempValueResultStatic;}if ((((((_unconverted_120) - (_halfref_160)))) > ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((512L))))))){{ahdlDoSetLineNum ((long) 35);ahdlDoSetLineNum ((long) 35);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_vLogicHigh_96);(_vd_312((_i_572))) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 36);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_unconverted_120) - (_halfref_160))));__tmpStkVar_1 = (__tmpStkVar_1);(_unconverted_120) = __tempValueResultStatic;}}}else{{ahdlDoSetLineNum ((long) 38);ahdlDoSetLineNum ((long) 38);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (_vlogic_low_200);(_vd_312((_i_572))) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 40);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_unconverted_120) * __INT_TO_DBL((2L)))));__tmpStkVar_1 = ((((__tmpStkVar_1)) * (__INT_TO_DBL((2L)))));(_unconverted_120) = __tempValueResultStatic;}}}ahdlDoSetLineNum ((long) 70);(_V_Static_DATA_7__592) += (_vd_312((7L)));ahdlDoSetLineNum ((long) 71);(_V_Static_DATA_6__624) += (_vd_312((6L)));ahdlDoSetLineNum ((long) 72);(_V_Static_DATA_5__656) += (_vd_312((5L)));ahdlDoSetLineNum ((long) 73);(_V_Static_DATA_4__688) += (_vd_312((4L)));ahdlDoSetLineNum ((long) 74);(_V_Static_DATA_3__720) += (_vd_312((3L)));ahdlDoSetLineNum ((long) 75);(_V_Static_DATA_2__752) += (_vd_312((2L)));ahdlDoSetLineNum ((long) 76);(_V_Static_DATA_1__784) += (_vd_312((1L)));ahdlDoSetLineNum ((long) 77);(_V_Static_DATA_0__816) += (_vd_312((0L)));}ahdlDoSetLineNum ((long) 82);    ahdlInterSetAcrossQuan(      *(void **)(instData + 584),
       _DATA_16,       *(long*)(instData + 0),       _DATA_7__flow_580,      _V_Static_DATA_7__592   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 612),
       *(long*)(instData + 20),       *(long*)(instData + 0),       _DATA_6__flow_608,      _V_Static_DATA_6__624   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 644),
       *(long*)(instData + 24),       *(long*)(instData + 0),       _DATA_5__flow_640,      _V_Static_DATA_5__656   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 676),
       *(long*)(instData + 28),       *(long*)(instData + 0),       _DATA_4__flow_672,      _V_Static_DATA_4__688   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 708),
       *(long*)(instData + 32),       *(long*)(instData + 0),       _DATA_3__flow_704,      _V_Static_DATA_3__720   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 740),
       *(long*)(instData + 36),       *(long*)(instData + 0),       _DATA_2__flow_736,      _V_Static_DATA_2__752   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 772),
       *(long*)(instData + 40),       *(long*)(instData + 0),       _DATA_1__flow_768,      _V_Static_DATA_1__784   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 804),
       *(long*)(instData + 44),       *(long*)(instData + 0),       _DATA_0__flow_800,      _V_Static_DATA_0__816   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimAdc_TranFuncDerLoad **/

int daisySimAdc_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */memcpy ((void *) (instData + 312), (void *) (instData + 440), 128);
_V_Static_DATA_7__592 = 0.0;
_V_Static_DATA_6__624 = 0.0;
_V_Static_DATA_5__656 = 0.0;
_V_Static_DATA_4__688 = 0.0;
_V_Static_DATA_3__720 = 0.0;
_V_Static_DATA_2__752 = 0.0;
_V_Static_DATA_1__784 = 0.0;
_V_Static_DATA_0__816 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 24);ahdlDoSetLineNum ((long) 24);(_vtrans_clk_240) = ((__FLOAT_DIV((_vLogicHigh_96), ((2.00000000000000000000e+00)))));ahdlDoSetLineNum ((long) 25);(_vlogic_low_200) = ((0.00000000000000000000e+00));ahdlDoSetLineNum ((long) 26);(_vref_280) = __INT_TO_DBL((1L));ahdlDoSetLineNum ((long) 27);(_halfref_160) = ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((2L)))));ahdlDoSetLineNum ((long) 31);(_unconverted_120) = ((getAcrossSolution1(_vin_52)));ahdlDoSetLineNum ((long) 32);for (_i_572 = (7L); (((_i_572)) >= ((0L))); _i_572 = (((_i_572) - ((1L))))){{ahdlDoSetLineNum ((long) 33);ahdlDoSetLineNum ((long) 33);(_vd_312((_i_572))) = __INT_TO_DBL((0L));if ((((((_unconverted_120) - (_halfref_160)))) > ((__FLOAT_DIV((_vref_280), __INT_TO_DBL((512L))))))){{ahdlDoSetLineNum ((long) 35);ahdlDoSetLineNum ((long) 35);(_vd_312((_i_572))) = (_vLogicHigh_96);ahdlDoSetLineNum ((long) 36);(_unconverted_120) = ((((_unconverted_120) - (_halfref_160))));}}else{{ahdlDoSetLineNum ((long) 38);ahdlDoSetLineNum ((long) 38);(_vd_312((_i_572))) = (_vlogic_low_200);}}ahdlDoSetLineNum ((long) 40);(_unconverted_120) = ((((_unconverted_120) * __INT_TO_DBL((2L)))));}}ahdlDoSetLineNum ((long) 70);(_V_Static_DATA_7__592) += (_vd_312((7L)));ahdlDoSetLineNum ((long) 71);(_V_Static_DATA_6__624) += (_vd_312((6L)));ahdlDoSetLineNum ((long) 72);(_V_Static_DATA_5__656) += (_vd_312((5L)));ahdlDoSetLineNum ((long) 73);(_V_Static_DATA_4__688) += (_vd_312((4L)));ahdlDoSetLineNum ((long) 74);(_V_Static_DATA_3__720) += (_vd_312((3L)));ahdlDoSetLineNum ((long) 75);(_V_Static_DATA_2__752) += (_vd_312((2L)));ahdlDoSetLineNum ((long) 76);(_V_Static_DATA_1__784) += (_vd_312((1L)));ahdlDoSetLineNum ((long) 77);(_V_Static_DATA_0__816) += (_vd_312((0L)));}ahdlDoSetLineNum ((long) 82);    ahdlInterSetAcrossQuan(      *(void **)(instData + 584),
       _DATA_16,       *(long*)(instData + 0),       _DATA_7__flow_580,      _V_Static_DATA_7__592   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 612),
       *(long*)(instData + 20),       *(long*)(instData + 0),       _DATA_6__flow_608,      _V_Static_DATA_6__624   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 644),
       *(long*)(instData + 24),       *(long*)(instData + 0),       _DATA_5__flow_640,      _V_Static_DATA_5__656   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 676),
       *(long*)(instData + 28),       *(long*)(instData + 0),       _DATA_4__flow_672,      _V_Static_DATA_4__688   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 708),
       *(long*)(instData + 32),       *(long*)(instData + 0),       _DATA_3__flow_704,      _V_Static_DATA_3__720   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 740),
       *(long*)(instData + 36),       *(long*)(instData + 0),       _DATA_2__flow_736,      _V_Static_DATA_2__752   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 772),
       *(long*)(instData + 40),       *(long*)(instData + 0),       _DATA_1__flow_768,      _V_Static_DATA_1__784   ,       1.0    );
    ahdlInterSetAcrossQuan(      *(void **)(instData + 804),
       *(long*)(instData + 44),       *(long*)(instData + 0),       _DATA_0__flow_800,      _V_Static_DATA_0__816   ,       1.0    );
    return __msgSeverity__;
} /** end of daisySimAdc_TranFuncLoad **/

int daisySimAdc_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of daisySimAdc_NoiseLoadBiasDep **/

int daisySimAdc_OpPointCalc(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
    return __msgSeverity__;
} /** end of daisySimAdc_OpPointCalc **/

