/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include "ahdlcmi.h"

int ahdlBsourceInterfaceVersion() {
   return 1; /* Only used when version >= spectre's BsourceInterfaceVersion */
}

extern int daisySimAdc_DcFuncDerLoad(int, char*, char*, char**);
extern int daisySimAdc_DcFuncLoad(int, char*, char*, char**);
extern int daisySimAdc_TranFuncDerLoad(int, char*, char*, char**);
extern int daisySimAdc_TranFuncLoad(int, char*, char*, char**);
extern int daisySimAdc_NoiseLoadBiasDep(int, char*, char*, char**);
extern int daisySimAdc_OpPointCalc(int, char*, char*, char**);

int daisySimAdc_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        daisySimAdc_DcFuncDerLoad,  
                        daisySimAdc_DcFuncLoad,     
                        daisySimAdc_TranFuncDerLoad,
                        daisySimAdc_TranFuncLoad,   
                        daisySimAdc_NoiseLoadBiasDep,
                        daisySimAdc_OpPointCalc
                       );
   return 1; /** success **/
}
extern int siconSimADC_DcFuncDerLoad(int, char*, char*, char**);
extern int siconSimADC_DcFuncLoad(int, char*, char*, char**);
extern int siconSimADC_TranFuncDerLoad(int, char*, char*, char**);
extern int siconSimADC_TranFuncLoad(int, char*, char*, char**);
extern int siconSimADC_NoiseLoadBiasDep(int, char*, char*, char**);
extern int siconSimADC_OpPointCalc(int, char*, char*, char**);

int siconSimADC_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        siconSimADC_DcFuncDerLoad,  
                        siconSimADC_DcFuncLoad,     
                        siconSimADC_TranFuncDerLoad,
                        siconSimADC_TranFuncLoad,   
                        siconSimADC_NoiseLoadBiasDep,
                        siconSimADC_OpPointCalc
                       );
   return 1; /** success **/
}
